// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	"github.com/steven-peralta/rosiebot/internal/app"
	"github.com/steven-peralta/rosiebot/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewAlertStore creates a new instance of AlertStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAlertStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *AlertStore {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &AlertStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// AlertStore is an autogenerated mock type for the AlertStore type
type AlertStore struct {
	mock.Mock
}

type AlertStore_Expecter struct {
	mock *mock.Mock
}

func (_m *AlertStore) EXPECT() *AlertStore_Expecter {
	return &AlertStore_Expecter{mock: &_m.Mock}
}

// ClearDMClosed provides a mock function for the type AlertStore
func (_mock *AlertStore) ClearDMClosed(ctx context.Context, userID string) error {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ClearDMClosed")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// AlertStore_ClearDMClosed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClearDMClosed'
type AlertStore_ClearDMClosed_Call struct {
	*mock.Call
}

// ClearDMClosed is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *AlertStore_Expecter) ClearDMClosed(ctx any, userID any) *AlertStore_ClearDMClosed_Call {
	return &AlertStore_ClearDMClosed_Call{Call: _e.mock.On("ClearDMClosed", ctx, userID)}
}

func (_c *AlertStore_ClearDMClosed_Call) Run(run func(ctx context.Context, userID string)) *AlertStore_ClearDMClosed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AlertStore_ClearDMClosed_Call) Return(err error) *AlertStore_ClearDMClosed_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *AlertStore_ClearDMClosed_Call) RunAndReturn(run func(ctx context.Context, userID string) error) *AlertStore_ClearDMClosed_Call {
	_c.Call.Return(run)
	return _c
}

// MarkDMClosed provides a mock function for the type AlertStore
func (_mock *AlertStore) MarkDMClosed(ctx context.Context, userID string, now time.Time) error {
	ret := _mock.Called(ctx, userID, now)

	if len(ret) == 0 {
		panic("no return value specified for MarkDMClosed")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Time) error); ok {
		r0 = returnFunc(ctx, userID, now)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// AlertStore_MarkDMClosed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkDMClosed'
type AlertStore_MarkDMClosed_Call struct {
	*mock.Call
}

// MarkDMClosed is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - now time.Time
func (_e *AlertStore_Expecter) MarkDMClosed(ctx any, userID any, now any) *AlertStore_MarkDMClosed_Call {
	return &AlertStore_MarkDMClosed_Call{Call: _e.mock.On("MarkDMClosed", ctx, userID, now)}
}

func (_c *AlertStore_MarkDMClosed_Call) Run(run func(ctx context.Context, userID string, now time.Time)) *AlertStore_MarkDMClosed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *AlertStore_MarkDMClosed_Call) Return(err error) *AlertStore_MarkDMClosed_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *AlertStore_MarkDMClosed_Call) RunAndReturn(run func(ctx context.Context, userID string, now time.Time) error) *AlertStore_MarkDMClosed_Call {
	_c.Call.Return(run)
	return _c
}

// MarkSent provides a mock function for the type AlertStore
func (_mock *AlertStore) MarkSent(ctx context.Context, eventID string, userID string, now time.Time) (bool, error) {
	ret := _mock.Called(ctx, eventID, userID, now)

	if len(ret) == 0 {
		panic("no return value specified for MarkSent")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, time.Time) (bool, error)); ok {
		return returnFunc(ctx, eventID, userID, now)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, time.Time) bool); ok {
		r0 = returnFunc(ctx, eventID, userID, now)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, time.Time) error); ok {
		r1 = returnFunc(ctx, eventID, userID, now)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AlertStore_MarkSent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkSent'
type AlertStore_MarkSent_Call struct {
	*mock.Call
}

// MarkSent is a helper method to define mock.On call
//   - ctx context.Context
//   - eventID string
//   - userID string
//   - now time.Time
func (_e *AlertStore_Expecter) MarkSent(ctx any, eventID any, userID any, now any) *AlertStore_MarkSent_Call {
	return &AlertStore_MarkSent_Call{Call: _e.mock.On("MarkSent", ctx, eventID, userID, now)}
}

func (_c *AlertStore_MarkSent_Call) Run(run func(ctx context.Context, eventID string, userID string, now time.Time)) *AlertStore_MarkSent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *AlertStore_MarkSent_Call) Return(first bool, err error) *AlertStore_MarkSent_Call {
	_c.Call.Return(first, err)
	return _c
}

func (_c *AlertStore_MarkSent_Call) RunAndReturn(run func(ctx context.Context, eventID string, userID string, now time.Time) (bool, error)) *AlertStore_MarkSent_Call {
	_c.Call.Return(run)
	return _c
}

// SetEnabled provides a mock function for the type AlertStore
func (_mock *AlertStore) SetEnabled(ctx context.Context, key domain.PlayerKey, enabled bool, now time.Time) error {
	ret := _mock.Called(ctx, key, enabled, now)

	if len(ret) == 0 {
		panic("no return value specified for SetEnabled")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.PlayerKey, bool, time.Time) error); ok {
		r0 = returnFunc(ctx, key, enabled, now)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// AlertStore_SetEnabled_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetEnabled'
type AlertStore_SetEnabled_Call struct {
	*mock.Call
}

// SetEnabled is a helper method to define mock.On call
//   - ctx context.Context
//   - key domain.PlayerKey
//   - enabled bool
//   - now time.Time
func (_e *AlertStore_Expecter) SetEnabled(ctx any, key any, enabled any, now any) *AlertStore_SetEnabled_Call {
	return &AlertStore_SetEnabled_Call{Call: _e.mock.On("SetEnabled", ctx, key, enabled, now)}
}

func (_c *AlertStore_SetEnabled_Call) Run(run func(ctx context.Context, key domain.PlayerKey, enabled bool, now time.Time)) *AlertStore_SetEnabled_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.PlayerKey
		if args[1] != nil {
			arg1 = args[1].(domain.PlayerKey)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *AlertStore_SetEnabled_Call) Return(err error) *AlertStore_SetEnabled_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *AlertStore_SetEnabled_Call) RunAndReturn(run func(ctx context.Context, key domain.PlayerKey, enabled bool, now time.Time) error) *AlertStore_SetEnabled_Call {
	_c.Call.Return(run)
	return _c
}

// Setting provides a mock function for the type AlertStore
func (_mock *AlertStore) Setting(ctx context.Context, key domain.PlayerKey) (app.AlertSetting, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Setting")
	}

	var r0 app.AlertSetting
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.PlayerKey) (app.AlertSetting, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.PlayerKey) app.AlertSetting); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Get(0).(app.AlertSetting)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.PlayerKey) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AlertStore_Setting_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Setting'
type AlertStore_Setting_Call struct {
	*mock.Call
}

// Setting is a helper method to define mock.On call
//   - ctx context.Context
//   - key domain.PlayerKey
func (_e *AlertStore_Expecter) Setting(ctx any, key any) *AlertStore_Setting_Call {
	return &AlertStore_Setting_Call{Call: _e.mock.On("Setting", ctx, key)}
}

func (_c *AlertStore_Setting_Call) Run(run func(ctx context.Context, key domain.PlayerKey)) *AlertStore_Setting_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.PlayerKey
		if args[1] != nil {
			arg1 = args[1].(domain.PlayerKey)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AlertStore_Setting_Call) Return(alertSetting app.AlertSetting, err error) *AlertStore_Setting_Call {
	_c.Call.Return(alertSetting, err)
	return _c
}

func (_c *AlertStore_Setting_Call) RunAndReturn(run func(ctx context.Context, key domain.PlayerKey) (app.AlertSetting, error)) *AlertStore_Setting_Call {
	_c.Call.Return(run)
	return _c
}
