// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	"github.com/steven-peralta/rosiebot/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewBannerStore creates a new instance of BannerStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBannerStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *BannerStore {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &BannerStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// BannerStore is an autogenerated mock type for the BannerStore type
type BannerStore struct {
	mock.Mock
}

type BannerStore_Expecter struct {
	mock *mock.Mock
}

func (_m *BannerStore) EXPECT() *BannerStore_Expecter {
	return &BannerStore_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type BannerStore
func (_mock *BannerStore) Get(ctx context.Context, weekStart time.Time) (domain.Banner, error) {
	ret := _mock.Called(ctx, weekStart)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 domain.Banner
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time) (domain.Banner, error)); ok {
		return returnFunc(ctx, weekStart)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time) domain.Banner); ok {
		r0 = returnFunc(ctx, weekStart)
	} else {
		r0 = ret.Get(0).(domain.Banner)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, time.Time) error); ok {
		r1 = returnFunc(ctx, weekStart)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// BannerStore_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type BannerStore_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - weekStart time.Time
func (_e *BannerStore_Expecter) Get(ctx any, weekStart any) *BannerStore_Get_Call {
	return &BannerStore_Get_Call{Call: _e.mock.On("Get", ctx, weekStart)}
}

func (_c *BannerStore_Get_Call) Run(run func(ctx context.Context, weekStart time.Time)) *BannerStore_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 time.Time
		if args[1] != nil {
			arg1 = args[1].(time.Time)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *BannerStore_Get_Call) Return(banner domain.Banner, err error) *BannerStore_Get_Call {
	_c.Call.Return(banner, err)
	return _c
}

func (_c *BannerStore_Get_Call) RunAndReturn(run func(ctx context.Context, weekStart time.Time) (domain.Banner, error)) *BannerStore_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Put provides a mock function for the type BannerStore
func (_mock *BannerStore) Put(ctx context.Context, b domain.Banner) (domain.Banner, error) {
	ret := _mock.Called(ctx, b)

	if len(ret) == 0 {
		panic("no return value specified for Put")
	}

	var r0 domain.Banner
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Banner) (domain.Banner, error)); ok {
		return returnFunc(ctx, b)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Banner) domain.Banner); ok {
		r0 = returnFunc(ctx, b)
	} else {
		r0 = ret.Get(0).(domain.Banner)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.Banner) error); ok {
		r1 = returnFunc(ctx, b)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// BannerStore_Put_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Put'
type BannerStore_Put_Call struct {
	*mock.Call
}

// Put is a helper method to define mock.On call
//   - ctx context.Context
//   - b domain.Banner
func (_e *BannerStore_Expecter) Put(ctx any, b any) *BannerStore_Put_Call {
	return &BannerStore_Put_Call{Call: _e.mock.On("Put", ctx, b)}
}

func (_c *BannerStore_Put_Call) Run(run func(ctx context.Context, b domain.Banner)) *BannerStore_Put_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Banner
		if args[1] != nil {
			arg1 = args[1].(domain.Banner)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *BannerStore_Put_Call) Return(banner domain.Banner, err error) *BannerStore_Put_Call {
	_c.Call.Return(banner, err)
	return _c
}

func (_c *BannerStore_Put_Call) RunAndReturn(run func(ctx context.Context, b domain.Banner) (domain.Banner, error)) *BannerStore_Put_Call {
	_c.Call.Return(run)
	return _c
}

// Replace provides a mock function for the type BannerStore
func (_mock *BannerStore) Replace(ctx context.Context, b domain.Banner) error {
	ret := _mock.Called(ctx, b)

	if len(ret) == 0 {
		panic("no return value specified for Replace")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Banner) error); ok {
		r0 = returnFunc(ctx, b)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// BannerStore_Replace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Replace'
type BannerStore_Replace_Call struct {
	*mock.Call
}

// Replace is a helper method to define mock.On call
//   - ctx context.Context
//   - b domain.Banner
func (_e *BannerStore_Expecter) Replace(ctx any, b any) *BannerStore_Replace_Call {
	return &BannerStore_Replace_Call{Call: _e.mock.On("Replace", ctx, b)}
}

func (_c *BannerStore_Replace_Call) Run(run func(ctx context.Context, b domain.Banner)) *BannerStore_Replace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Banner
		if args[1] != nil {
			arg1 = args[1].(domain.Banner)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *BannerStore_Replace_Call) Return(err error) *BannerStore_Replace_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *BannerStore_Replace_Call) RunAndReturn(run func(ctx context.Context, b domain.Banner) error) *BannerStore_Replace_Call {
	_c.Call.Return(run)
	return _c
}
