// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	"github.com/steven-peralta/rosiebot/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewDailyStore creates a new instance of DailyStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDailyStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *DailyStore {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &DailyStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// DailyStore is an autogenerated mock type for the DailyStore type
type DailyStore struct {
	mock.Mock
}

type DailyStore_Expecter struct {
	mock *mock.Mock
}

func (_m *DailyStore) EXPECT() *DailyStore_Expecter {
	return &DailyStore_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type DailyStore
func (_mock *DailyStore) Get(ctx context.Context, day time.Time) (domain.WaifuSummary, error) {
	ret := _mock.Called(ctx, day)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 domain.WaifuSummary
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time) (domain.WaifuSummary, error)); ok {
		return returnFunc(ctx, day)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time) domain.WaifuSummary); ok {
		r0 = returnFunc(ctx, day)
	} else {
		r0 = ret.Get(0).(domain.WaifuSummary)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, time.Time) error); ok {
		r1 = returnFunc(ctx, day)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DailyStore_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type DailyStore_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - day time.Time
func (_e *DailyStore_Expecter) Get(ctx any, day any) *DailyStore_Get_Call {
	return &DailyStore_Get_Call{Call: _e.mock.On("Get", ctx, day)}
}

func (_c *DailyStore_Get_Call) Run(run func(ctx context.Context, day time.Time)) *DailyStore_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 time.Time
		if args[1] != nil {
			arg1 = args[1].(time.Time)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *DailyStore_Get_Call) Return(waifuSummary domain.WaifuSummary, err error) *DailyStore_Get_Call {
	_c.Call.Return(waifuSummary, err)
	return _c
}

func (_c *DailyStore_Get_Call) RunAndReturn(run func(ctx context.Context, day time.Time) (domain.WaifuSummary, error)) *DailyStore_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Put provides a mock function for the type DailyStore
func (_mock *DailyStore) Put(ctx context.Context, day time.Time, w domain.WaifuSummary) (domain.WaifuSummary, error) {
	ret := _mock.Called(ctx, day, w)

	if len(ret) == 0 {
		panic("no return value specified for Put")
	}

	var r0 domain.WaifuSummary
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time, domain.WaifuSummary) (domain.WaifuSummary, error)); ok {
		return returnFunc(ctx, day, w)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time, domain.WaifuSummary) domain.WaifuSummary); ok {
		r0 = returnFunc(ctx, day, w)
	} else {
		r0 = ret.Get(0).(domain.WaifuSummary)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, time.Time, domain.WaifuSummary) error); ok {
		r1 = returnFunc(ctx, day, w)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DailyStore_Put_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Put'
type DailyStore_Put_Call struct {
	*mock.Call
}

// Put is a helper method to define mock.On call
//   - ctx context.Context
//   - day time.Time
//   - w domain.WaifuSummary
func (_e *DailyStore_Expecter) Put(ctx any, day any, w any) *DailyStore_Put_Call {
	return &DailyStore_Put_Call{Call: _e.mock.On("Put", ctx, day, w)}
}

func (_c *DailyStore_Put_Call) Run(run func(ctx context.Context, day time.Time, w domain.WaifuSummary)) *DailyStore_Put_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 time.Time
		if args[1] != nil {
			arg1 = args[1].(time.Time)
		}
		var arg2 domain.WaifuSummary
		if args[2] != nil {
			arg2 = args[2].(domain.WaifuSummary)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *DailyStore_Put_Call) Return(waifuSummary domain.WaifuSummary, err error) *DailyStore_Put_Call {
	_c.Call.Return(waifuSummary, err)
	return _c
}

func (_c *DailyStore_Put_Call) RunAndReturn(run func(ctx context.Context, day time.Time, w domain.WaifuSummary) (domain.WaifuSummary, error)) *DailyStore_Put_Call {
	_c.Call.Return(run)
	return _c
}
