// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/steven-peralta/rosiebot/internal/app"
	"github.com/steven-peralta/rosiebot/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewFavoriteStore creates a new instance of FavoriteStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFavoriteStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *FavoriteStore {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &FavoriteStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// FavoriteStore is an autogenerated mock type for the FavoriteStore type
type FavoriteStore struct {
	mock.Mock
}

type FavoriteStore_Expecter struct {
	mock *mock.Mock
}

func (_m *FavoriteStore) EXPECT() *FavoriteStore_Expecter {
	return &FavoriteStore_Expecter{mock: &_m.Mock}
}

// Add provides a mock function for the type FavoriteStore
func (_mock *FavoriteStore) Add(ctx context.Context, key domain.PlayerKey, fav domain.Favorite) (bool, error) {
	ret := _mock.Called(ctx, key, fav)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.PlayerKey, domain.Favorite) (bool, error)); ok {
		return returnFunc(ctx, key, fav)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.PlayerKey, domain.Favorite) bool); ok {
		r0 = returnFunc(ctx, key, fav)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.PlayerKey, domain.Favorite) error); ok {
		r1 = returnFunc(ctx, key, fav)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// FavoriteStore_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type FavoriteStore_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - ctx context.Context
//   - key domain.PlayerKey
//   - fav domain.Favorite
func (_e *FavoriteStore_Expecter) Add(ctx any, key any, fav any) *FavoriteStore_Add_Call {
	return &FavoriteStore_Add_Call{Call: _e.mock.On("Add", ctx, key, fav)}
}

func (_c *FavoriteStore_Add_Call) Run(run func(ctx context.Context, key domain.PlayerKey, fav domain.Favorite)) *FavoriteStore_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.PlayerKey
		if args[1] != nil {
			arg1 = args[1].(domain.PlayerKey)
		}
		var arg2 domain.Favorite
		if args[2] != nil {
			arg2 = args[2].(domain.Favorite)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *FavoriteStore_Add_Call) Return(added bool, err error) *FavoriteStore_Add_Call {
	_c.Call.Return(added, err)
	return _c
}

func (_c *FavoriteStore_Add_Call) RunAndReturn(run func(ctx context.Context, key domain.PlayerKey, fav domain.Favorite) (bool, error)) *FavoriteStore_Add_Call {
	_c.Call.Return(run)
	return _c
}

// Find provides a mock function for the type FavoriteStore
func (_mock *FavoriteStore) Find(ctx context.Context, kind domain.FavoriteKind, slugs []string, guildID string) ([]app.FavoriteMatch, error) {
	ret := _mock.Called(ctx, kind, slugs, guildID)

	if len(ret) == 0 {
		panic("no return value specified for Find")
	}

	var r0 []app.FavoriteMatch
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.FavoriteKind, []string, string) ([]app.FavoriteMatch, error)); ok {
		return returnFunc(ctx, kind, slugs, guildID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.FavoriteKind, []string, string) []app.FavoriteMatch); ok {
		r0 = returnFunc(ctx, kind, slugs, guildID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]app.FavoriteMatch)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.FavoriteKind, []string, string) error); ok {
		r1 = returnFunc(ctx, kind, slugs, guildID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// FavoriteStore_Find_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Find'
type FavoriteStore_Find_Call struct {
	*mock.Call
}

// Find is a helper method to define mock.On call
//   - ctx context.Context
//   - kind domain.FavoriteKind
//   - slugs []string
//   - guildID string
func (_e *FavoriteStore_Expecter) Find(ctx any, kind any, slugs any, guildID any) *FavoriteStore_Find_Call {
	return &FavoriteStore_Find_Call{Call: _e.mock.On("Find", ctx, kind, slugs, guildID)}
}

func (_c *FavoriteStore_Find_Call) Run(run func(ctx context.Context, kind domain.FavoriteKind, slugs []string, guildID string)) *FavoriteStore_Find_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.FavoriteKind
		if args[1] != nil {
			arg1 = args[1].(domain.FavoriteKind)
		}
		var arg2 []string
		if args[2] != nil {
			arg2 = args[2].([]string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *FavoriteStore_Find_Call) Return(favoriteMatchs []app.FavoriteMatch, err error) *FavoriteStore_Find_Call {
	_c.Call.Return(favoriteMatchs, err)
	return _c
}

func (_c *FavoriteStore_Find_Call) RunAndReturn(run func(ctx context.Context, kind domain.FavoriteKind, slugs []string, guildID string) ([]app.FavoriteMatch, error)) *FavoriteStore_Find_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type FavoriteStore
func (_mock *FavoriteStore) List(ctx context.Context, key domain.PlayerKey, kind domain.FavoriteKind) ([]domain.Favorite, error) {
	ret := _mock.Called(ctx, key, kind)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []domain.Favorite
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.PlayerKey, domain.FavoriteKind) ([]domain.Favorite, error)); ok {
		return returnFunc(ctx, key, kind)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.PlayerKey, domain.FavoriteKind) []domain.Favorite); ok {
		r0 = returnFunc(ctx, key, kind)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Favorite)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.PlayerKey, domain.FavoriteKind) error); ok {
		r1 = returnFunc(ctx, key, kind)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// FavoriteStore_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type FavoriteStore_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - key domain.PlayerKey
//   - kind domain.FavoriteKind
func (_e *FavoriteStore_Expecter) List(ctx any, key any, kind any) *FavoriteStore_List_Call {
	return &FavoriteStore_List_Call{Call: _e.mock.On("List", ctx, key, kind)}
}

func (_c *FavoriteStore_List_Call) Run(run func(ctx context.Context, key domain.PlayerKey, kind domain.FavoriteKind)) *FavoriteStore_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.PlayerKey
		if args[1] != nil {
			arg1 = args[1].(domain.PlayerKey)
		}
		var arg2 domain.FavoriteKind
		if args[2] != nil {
			arg2 = args[2].(domain.FavoriteKind)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *FavoriteStore_List_Call) Return(favorites []domain.Favorite, err error) *FavoriteStore_List_Call {
	_c.Call.Return(favorites, err)
	return _c
}

func (_c *FavoriteStore_List_Call) RunAndReturn(run func(ctx context.Context, key domain.PlayerKey, kind domain.FavoriteKind) ([]domain.Favorite, error)) *FavoriteStore_List_Call {
	_c.Call.Return(run)
	return _c
}

// Remove provides a mock function for the type FavoriteStore
func (_mock *FavoriteStore) Remove(ctx context.Context, key domain.PlayerKey, kind domain.FavoriteKind, slug string) (bool, error) {
	ret := _mock.Called(ctx, key, kind, slug)

	if len(ret) == 0 {
		panic("no return value specified for Remove")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.PlayerKey, domain.FavoriteKind, string) (bool, error)); ok {
		return returnFunc(ctx, key, kind, slug)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.PlayerKey, domain.FavoriteKind, string) bool); ok {
		r0 = returnFunc(ctx, key, kind, slug)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.PlayerKey, domain.FavoriteKind, string) error); ok {
		r1 = returnFunc(ctx, key, kind, slug)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// FavoriteStore_Remove_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Remove'
type FavoriteStore_Remove_Call struct {
	*mock.Call
}

// Remove is a helper method to define mock.On call
//   - ctx context.Context
//   - key domain.PlayerKey
//   - kind domain.FavoriteKind
//   - slug string
func (_e *FavoriteStore_Expecter) Remove(ctx any, key any, kind any, slug any) *FavoriteStore_Remove_Call {
	return &FavoriteStore_Remove_Call{Call: _e.mock.On("Remove", ctx, key, kind, slug)}
}

func (_c *FavoriteStore_Remove_Call) Run(run func(ctx context.Context, key domain.PlayerKey, kind domain.FavoriteKind, slug string)) *FavoriteStore_Remove_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.PlayerKey
		if args[1] != nil {
			arg1 = args[1].(domain.PlayerKey)
		}
		var arg2 domain.FavoriteKind
		if args[2] != nil {
			arg2 = args[2].(domain.FavoriteKind)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *FavoriteStore_Remove_Call) Return(removed bool, err error) *FavoriteStore_Remove_Call {
	_c.Call.Return(removed, err)
	return _c
}

func (_c *FavoriteStore_Remove_Call) RunAndReturn(run func(ctx context.Context, key domain.PlayerKey, kind domain.FavoriteKind, slug string) (bool, error)) *FavoriteStore_Remove_Call {
	_c.Call.Return(run)
	return _c
}
