// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewNotifier creates a new instance of Notifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNotifier(t interface {
	mock.TestingT
	Cleanup(func())
}) *Notifier {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &Notifier{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// Notifier is an autogenerated mock type for the Notifier type
type Notifier struct {
	mock.Mock
}

type Notifier_Expecter struct {
	mock *mock.Mock
}

func (_m *Notifier) EXPECT() *Notifier_Expecter {
	return &Notifier_Expecter{mock: &_m.Mock}
}

// DirectMessage provides a mock function for the type Notifier
func (_mock *Notifier) DirectMessage(ctx context.Context, userID string, content string) error {
	ret := _mock.Called(ctx, userID, content)

	if len(ret) == 0 {
		panic("no return value specified for DirectMessage")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, userID, content)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Notifier_DirectMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DirectMessage'
type Notifier_DirectMessage_Call struct {
	*mock.Call
}

// DirectMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - content string
func (_e *Notifier_Expecter) DirectMessage(ctx any, userID any, content any) *Notifier_DirectMessage_Call {
	return &Notifier_DirectMessage_Call{Call: _e.mock.On("DirectMessage", ctx, userID, content)}
}

func (_c *Notifier_DirectMessage_Call) Run(run func(ctx context.Context, userID string, content string)) *Notifier_DirectMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Notifier_DirectMessage_Call) Return(err error) *Notifier_DirectMessage_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Notifier_DirectMessage_Call) RunAndReturn(run func(ctx context.Context, userID string, content string) error) *Notifier_DirectMessage_Call {
	_c.Call.Return(run)
	return _c
}
