// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	"github.com/steven-peralta/rosiebot/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewPlayerRepo creates a new instance of PlayerRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPlayerRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *PlayerRepo {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &PlayerRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// PlayerRepo is an autogenerated mock type for the PlayerRepo type
type PlayerRepo struct {
	mock.Mock
}

type PlayerRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *PlayerRepo) EXPECT() *PlayerRepo_Expecter {
	return &PlayerRepo_Expecter{mock: &_m.Mock}
}

// AddOwned provides a mock function for the type PlayerRepo
func (_mock *PlayerRepo) AddOwned(ctx context.Context, key domain.PlayerKey, w domain.OwnedWaifu) (bool, error) {
	ret := _mock.Called(ctx, key, w)

	if len(ret) == 0 {
		panic("no return value specified for AddOwned")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.PlayerKey, domain.OwnedWaifu) (bool, error)); ok {
		return returnFunc(ctx, key, w)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.PlayerKey, domain.OwnedWaifu) bool); ok {
		r0 = returnFunc(ctx, key, w)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.PlayerKey, domain.OwnedWaifu) error); ok {
		r1 = returnFunc(ctx, key, w)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PlayerRepo_AddOwned_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddOwned'
type PlayerRepo_AddOwned_Call struct {
	*mock.Call
}

// AddOwned is a helper method to define mock.On call
//   - ctx context.Context
//   - key domain.PlayerKey
//   - w domain.OwnedWaifu
func (_e *PlayerRepo_Expecter) AddOwned(ctx any, key any, w any) *PlayerRepo_AddOwned_Call {
	return &PlayerRepo_AddOwned_Call{Call: _e.mock.On("AddOwned", ctx, key, w)}
}

func (_c *PlayerRepo_AddOwned_Call) Run(run func(ctx context.Context, key domain.PlayerKey, w domain.OwnedWaifu)) *PlayerRepo_AddOwned_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.PlayerKey
		if args[1] != nil {
			arg1 = args[1].(domain.PlayerKey)
		}
		var arg2 domain.OwnedWaifu
		if args[2] != nil {
			arg2 = args[2].(domain.OwnedWaifu)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *PlayerRepo_AddOwned_Call) Return(inserted bool, err error) *PlayerRepo_AddOwned_Call {
	_c.Call.Return(inserted, err)
	return _c
}

func (_c *PlayerRepo_AddOwned_Call) RunAndReturn(run func(ctx context.Context, key domain.PlayerKey, w domain.OwnedWaifu) (bool, error)) *PlayerRepo_AddOwned_Call {
	_c.Call.Return(run)
	return _c
}

// ClaimDaily provides a mock function for the type PlayerRepo
func (_mock *PlayerRepo) ClaimDaily(ctx context.Context, key domain.PlayerKey, amount int64, windowStart time.Time, now time.Time) (int64, bool, error) {
	ret := _mock.Called(ctx, key, amount, windowStart, now)

	if len(ret) == 0 {
		panic("no return value specified for ClaimDaily")
	}

	var r0 int64
	var r1 bool
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.PlayerKey, int64, time.Time, time.Time) (int64, bool, error)); ok {
		return returnFunc(ctx, key, amount, windowStart, now)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.PlayerKey, int64, time.Time, time.Time) int64); ok {
		r0 = returnFunc(ctx, key, amount, windowStart, now)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.PlayerKey, int64, time.Time, time.Time) bool); ok {
		r1 = returnFunc(ctx, key, amount, windowStart, now)
	} else {
		r1 = ret.Get(1).(bool)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, domain.PlayerKey, int64, time.Time, time.Time) error); ok {
		r2 = returnFunc(ctx, key, amount, windowStart, now)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// PlayerRepo_ClaimDaily_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClaimDaily'
type PlayerRepo_ClaimDaily_Call struct {
	*mock.Call
}

// ClaimDaily is a helper method to define mock.On call
//   - ctx context.Context
//   - key domain.PlayerKey
//   - amount int64
//   - windowStart time.Time
//   - now time.Time
func (_e *PlayerRepo_Expecter) ClaimDaily(ctx any, key any, amount any, windowStart any, now any) *PlayerRepo_ClaimDaily_Call {
	return &PlayerRepo_ClaimDaily_Call{Call: _e.mock.On("ClaimDaily", ctx, key, amount, windowStart, now)}
}

func (_c *PlayerRepo_ClaimDaily_Call) Run(run func(ctx context.Context, key domain.PlayerKey, amount int64, windowStart time.Time, now time.Time)) *PlayerRepo_ClaimDaily_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.PlayerKey
		if args[1] != nil {
			arg1 = args[1].(domain.PlayerKey)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		var arg4 time.Time
		if args[4] != nil {
			arg4 = args[4].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *PlayerRepo_ClaimDaily_Call) Return(balance int64, ok bool, err error) *PlayerRepo_ClaimDaily_Call {
	_c.Call.Return(balance, ok, err)
	return _c
}

func (_c *PlayerRepo_ClaimDaily_Call) RunAndReturn(run func(ctx context.Context, key domain.PlayerKey, amount int64, windowStart time.Time, now time.Time) (int64, bool, error)) *PlayerRepo_ClaimDaily_Call {
	_c.Call.Return(run)
	return _c
}

// CountOwned provides a mock function for the type PlayerRepo
func (_mock *PlayerRepo) CountOwned(ctx context.Context, key domain.PlayerKey) (int, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for CountOwned")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.PlayerKey) (int, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.PlayerKey) int); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.PlayerKey) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PlayerRepo_CountOwned_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountOwned'
type PlayerRepo_CountOwned_Call struct {
	*mock.Call
}

// CountOwned is a helper method to define mock.On call
//   - ctx context.Context
//   - key domain.PlayerKey
func (_e *PlayerRepo_Expecter) CountOwned(ctx any, key any) *PlayerRepo_CountOwned_Call {
	return &PlayerRepo_CountOwned_Call{Call: _e.mock.On("CountOwned", ctx, key)}
}

func (_c *PlayerRepo_CountOwned_Call) Run(run func(ctx context.Context, key domain.PlayerKey)) *PlayerRepo_CountOwned_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.PlayerKey
		if args[1] != nil {
			arg1 = args[1].(domain.PlayerKey)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *PlayerRepo_CountOwned_Call) Return(n int, err error) *PlayerRepo_CountOwned_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *PlayerRepo_CountOwned_Call) RunAndReturn(run func(ctx context.Context, key domain.PlayerKey) (int, error)) *PlayerRepo_CountOwned_Call {
	_c.Call.Return(run)
	return _c
}

// DebitCoins provides a mock function for the type PlayerRepo
func (_mock *PlayerRepo) DebitCoins(ctx context.Context, key domain.PlayerKey, amount int64) (int64, bool, error) {
	ret := _mock.Called(ctx, key, amount)

	if len(ret) == 0 {
		panic("no return value specified for DebitCoins")
	}

	var r0 int64
	var r1 bool
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.PlayerKey, int64) (int64, bool, error)); ok {
		return returnFunc(ctx, key, amount)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.PlayerKey, int64) int64); ok {
		r0 = returnFunc(ctx, key, amount)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.PlayerKey, int64) bool); ok {
		r1 = returnFunc(ctx, key, amount)
	} else {
		r1 = ret.Get(1).(bool)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, domain.PlayerKey, int64) error); ok {
		r2 = returnFunc(ctx, key, amount)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// PlayerRepo_DebitCoins_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DebitCoins'
type PlayerRepo_DebitCoins_Call struct {
	*mock.Call
}

// DebitCoins is a helper method to define mock.On call
//   - ctx context.Context
//   - key domain.PlayerKey
//   - amount int64
func (_e *PlayerRepo_Expecter) DebitCoins(ctx any, key any, amount any) *PlayerRepo_DebitCoins_Call {
	return &PlayerRepo_DebitCoins_Call{Call: _e.mock.On("DebitCoins", ctx, key, amount)}
}

func (_c *PlayerRepo_DebitCoins_Call) Run(run func(ctx context.Context, key domain.PlayerKey, amount int64)) *PlayerRepo_DebitCoins_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.PlayerKey
		if args[1] != nil {
			arg1 = args[1].(domain.PlayerKey)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *PlayerRepo_DebitCoins_Call) Return(balance int64, ok bool, err error) *PlayerRepo_DebitCoins_Call {
	_c.Call.Return(balance, ok, err)
	return _c
}

func (_c *PlayerRepo_DebitCoins_Call) RunAndReturn(run func(ctx context.Context, key domain.PlayerKey, amount int64) (int64, bool, error)) *PlayerRepo_DebitCoins_Call {
	_c.Call.Return(run)
	return _c
}

// EnsurePlayer provides a mock function for the type PlayerRepo
func (_mock *PlayerRepo) EnsurePlayer(ctx context.Context, key domain.PlayerKey) (domain.Player, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for EnsurePlayer")
	}

	var r0 domain.Player
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.PlayerKey) (domain.Player, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.PlayerKey) domain.Player); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Get(0).(domain.Player)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.PlayerKey) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PlayerRepo_EnsurePlayer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnsurePlayer'
type PlayerRepo_EnsurePlayer_Call struct {
	*mock.Call
}

// EnsurePlayer is a helper method to define mock.On call
//   - ctx context.Context
//   - key domain.PlayerKey
func (_e *PlayerRepo_Expecter) EnsurePlayer(ctx any, key any) *PlayerRepo_EnsurePlayer_Call {
	return &PlayerRepo_EnsurePlayer_Call{Call: _e.mock.On("EnsurePlayer", ctx, key)}
}

func (_c *PlayerRepo_EnsurePlayer_Call) Run(run func(ctx context.Context, key domain.PlayerKey)) *PlayerRepo_EnsurePlayer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.PlayerKey
		if args[1] != nil {
			arg1 = args[1].(domain.PlayerKey)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *PlayerRepo_EnsurePlayer_Call) Return(player domain.Player, err error) *PlayerRepo_EnsurePlayer_Call {
	_c.Call.Return(player, err)
	return _c
}

func (_c *PlayerRepo_EnsurePlayer_Call) RunAndReturn(run func(ctx context.Context, key domain.PlayerKey) (domain.Player, error)) *PlayerRepo_EnsurePlayer_Call {
	_c.Call.Return(run)
	return _c
}

// GetOwned provides a mock function for the type PlayerRepo
func (_mock *PlayerRepo) GetOwned(ctx context.Context, key domain.PlayerKey, slug string) (domain.OwnedWaifu, error) {
	ret := _mock.Called(ctx, key, slug)

	if len(ret) == 0 {
		panic("no return value specified for GetOwned")
	}

	var r0 domain.OwnedWaifu
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.PlayerKey, string) (domain.OwnedWaifu, error)); ok {
		return returnFunc(ctx, key, slug)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.PlayerKey, string) domain.OwnedWaifu); ok {
		r0 = returnFunc(ctx, key, slug)
	} else {
		r0 = ret.Get(0).(domain.OwnedWaifu)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.PlayerKey, string) error); ok {
		r1 = returnFunc(ctx, key, slug)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PlayerRepo_GetOwned_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOwned'
type PlayerRepo_GetOwned_Call struct {
	*mock.Call
}

// GetOwned is a helper method to define mock.On call
//   - ctx context.Context
//   - key domain.PlayerKey
//   - slug string
func (_e *PlayerRepo_Expecter) GetOwned(ctx any, key any, slug any) *PlayerRepo_GetOwned_Call {
	return &PlayerRepo_GetOwned_Call{Call: _e.mock.On("GetOwned", ctx, key, slug)}
}

func (_c *PlayerRepo_GetOwned_Call) Run(run func(ctx context.Context, key domain.PlayerKey, slug string)) *PlayerRepo_GetOwned_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.PlayerKey
		if args[1] != nil {
			arg1 = args[1].(domain.PlayerKey)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *PlayerRepo_GetOwned_Call) Return(ownedWaifu domain.OwnedWaifu, err error) *PlayerRepo_GetOwned_Call {
	_c.Call.Return(ownedWaifu, err)
	return _c
}

func (_c *PlayerRepo_GetOwned_Call) RunAndReturn(run func(ctx context.Context, key domain.PlayerKey, slug string) (domain.OwnedWaifu, error)) *PlayerRepo_GetOwned_Call {
	_c.Call.Return(run)
	return _c
}

// GetPlayer provides a mock function for the type PlayerRepo
func (_mock *PlayerRepo) GetPlayer(ctx context.Context, key domain.PlayerKey) (domain.Player, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for GetPlayer")
	}

	var r0 domain.Player
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.PlayerKey) (domain.Player, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.PlayerKey) domain.Player); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Get(0).(domain.Player)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.PlayerKey) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PlayerRepo_GetPlayer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPlayer'
type PlayerRepo_GetPlayer_Call struct {
	*mock.Call
}

// GetPlayer is a helper method to define mock.On call
//   - ctx context.Context
//   - key domain.PlayerKey
func (_e *PlayerRepo_Expecter) GetPlayer(ctx any, key any) *PlayerRepo_GetPlayer_Call {
	return &PlayerRepo_GetPlayer_Call{Call: _e.mock.On("GetPlayer", ctx, key)}
}

func (_c *PlayerRepo_GetPlayer_Call) Run(run func(ctx context.Context, key domain.PlayerKey)) *PlayerRepo_GetPlayer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.PlayerKey
		if args[1] != nil {
			arg1 = args[1].(domain.PlayerKey)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *PlayerRepo_GetPlayer_Call) Return(player domain.Player, err error) *PlayerRepo_GetPlayer_Call {
	_c.Call.Return(player, err)
	return _c
}

func (_c *PlayerRepo_GetPlayer_Call) RunAndReturn(run func(ctx context.Context, key domain.PlayerKey) (domain.Player, error)) *PlayerRepo_GetPlayer_Call {
	_c.Call.Return(run)
	return _c
}

// ListOwned provides a mock function for the type PlayerRepo
func (_mock *PlayerRepo) ListOwned(ctx context.Context, key domain.PlayerKey, prefix string, limit int) ([]domain.OwnedWaifu, error) {
	ret := _mock.Called(ctx, key, prefix, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListOwned")
	}

	var r0 []domain.OwnedWaifu
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.PlayerKey, string, int) ([]domain.OwnedWaifu, error)); ok {
		return returnFunc(ctx, key, prefix, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.PlayerKey, string, int) []domain.OwnedWaifu); ok {
		r0 = returnFunc(ctx, key, prefix, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.OwnedWaifu)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.PlayerKey, string, int) error); ok {
		r1 = returnFunc(ctx, key, prefix, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PlayerRepo_ListOwned_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListOwned'
type PlayerRepo_ListOwned_Call struct {
	*mock.Call
}

// ListOwned is a helper method to define mock.On call
//   - ctx context.Context
//   - key domain.PlayerKey
//   - prefix string
//   - limit int
func (_e *PlayerRepo_Expecter) ListOwned(ctx any, key any, prefix any, limit any) *PlayerRepo_ListOwned_Call {
	return &PlayerRepo_ListOwned_Call{Call: _e.mock.On("ListOwned", ctx, key, prefix, limit)}
}

func (_c *PlayerRepo_ListOwned_Call) Run(run func(ctx context.Context, key domain.PlayerKey, prefix string, limit int)) *PlayerRepo_ListOwned_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.PlayerKey
		if args[1] != nil {
			arg1 = args[1].(domain.PlayerKey)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *PlayerRepo_ListOwned_Call) Return(ownedWaifus []domain.OwnedWaifu, err error) *PlayerRepo_ListOwned_Call {
	_c.Call.Return(ownedWaifus, err)
	return _c
}

func (_c *PlayerRepo_ListOwned_Call) RunAndReturn(run func(ctx context.Context, key domain.PlayerKey, prefix string, limit int) ([]domain.OwnedWaifu, error)) *PlayerRepo_ListOwned_Call {
	_c.Call.Return(run)
	return _c
}

// LockPlayers provides a mock function for the type PlayerRepo
func (_mock *PlayerRepo) LockPlayers(ctx context.Context, keys ...domain.PlayerKey) ([]domain.Player, error) {
	var tmpRet mock.Arguments
	if len(keys) > 0 {
		tmpRet = _mock.Called(ctx, keys)
	} else {
		tmpRet = _mock.Called(ctx)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for LockPlayers")
	}

	var r0 []domain.Player
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...domain.PlayerKey) ([]domain.Player, error)); ok {
		return returnFunc(ctx, keys...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...domain.PlayerKey) []domain.Player); ok {
		r0 = returnFunc(ctx, keys...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Player)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ...domain.PlayerKey) error); ok {
		r1 = returnFunc(ctx, keys...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PlayerRepo_LockPlayers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LockPlayers'
type PlayerRepo_LockPlayers_Call struct {
	*mock.Call
}

// LockPlayers is a helper method to define mock.On call
//   - ctx context.Context
//   - keys ...domain.PlayerKey
func (_e *PlayerRepo_Expecter) LockPlayers(ctx any, keys ...any) *PlayerRepo_LockPlayers_Call {
	return &PlayerRepo_LockPlayers_Call{Call: _e.mock.On("LockPlayers",
		append([]any{ctx}, keys...)...)}
}

func (_c *PlayerRepo_LockPlayers_Call) Run(run func(ctx context.Context, keys ...domain.PlayerKey)) *PlayerRepo_LockPlayers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []domain.PlayerKey
		var variadicArgs []domain.PlayerKey
		if len(args) > 1 {
			variadicArgs = args[1].([]domain.PlayerKey)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *PlayerRepo_LockPlayers_Call) Return(players []domain.Player, err error) *PlayerRepo_LockPlayers_Call {
	_c.Call.Return(players, err)
	return _c
}

func (_c *PlayerRepo_LockPlayers_Call) RunAndReturn(run func(ctx context.Context, keys ...domain.PlayerKey) ([]domain.Player, error)) *PlayerRepo_LockPlayers_Call {
	_c.Call.Return(run)
	return _c
}

// OwnedSlugs provides a mock function for the type PlayerRepo
func (_mock *PlayerRepo) OwnedSlugs(ctx context.Context, key domain.PlayerKey, slugs []string) ([]string, error) {
	ret := _mock.Called(ctx, key, slugs)

	if len(ret) == 0 {
		panic("no return value specified for OwnedSlugs")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.PlayerKey, []string) ([]string, error)); ok {
		return returnFunc(ctx, key, slugs)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.PlayerKey, []string) []string); ok {
		r0 = returnFunc(ctx, key, slugs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.PlayerKey, []string) error); ok {
		r1 = returnFunc(ctx, key, slugs)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PlayerRepo_OwnedSlugs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OwnedSlugs'
type PlayerRepo_OwnedSlugs_Call struct {
	*mock.Call
}

// OwnedSlugs is a helper method to define mock.On call
//   - ctx context.Context
//   - key domain.PlayerKey
//   - slugs []string
func (_e *PlayerRepo_Expecter) OwnedSlugs(ctx any, key any, slugs any) *PlayerRepo_OwnedSlugs_Call {
	return &PlayerRepo_OwnedSlugs_Call{Call: _e.mock.On("OwnedSlugs", ctx, key, slugs)}
}

func (_c *PlayerRepo_OwnedSlugs_Call) Run(run func(ctx context.Context, key domain.PlayerKey, slugs []string)) *PlayerRepo_OwnedSlugs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.PlayerKey
		if args[1] != nil {
			arg1 = args[1].(domain.PlayerKey)
		}
		var arg2 []string
		if args[2] != nil {
			arg2 = args[2].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *PlayerRepo_OwnedSlugs_Call) Return(strings []string, err error) *PlayerRepo_OwnedSlugs_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *PlayerRepo_OwnedSlugs_Call) RunAndReturn(run func(ctx context.Context, key domain.PlayerKey, slugs []string) ([]string, error)) *PlayerRepo_OwnedSlugs_Call {
	_c.Call.Return(run)
	return _c
}

// SellOwned provides a mock function for the type PlayerRepo
func (_mock *PlayerRepo) SellOwned(ctx context.Context, key domain.PlayerKey, slug string, price int64) (int64, bool, error) {
	ret := _mock.Called(ctx, key, slug, price)

	if len(ret) == 0 {
		panic("no return value specified for SellOwned")
	}

	var r0 int64
	var r1 bool
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.PlayerKey, string, int64) (int64, bool, error)); ok {
		return returnFunc(ctx, key, slug, price)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.PlayerKey, string, int64) int64); ok {
		r0 = returnFunc(ctx, key, slug, price)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.PlayerKey, string, int64) bool); ok {
		r1 = returnFunc(ctx, key, slug, price)
	} else {
		r1 = ret.Get(1).(bool)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, domain.PlayerKey, string, int64) error); ok {
		r2 = returnFunc(ctx, key, slug, price)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// PlayerRepo_SellOwned_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SellOwned'
type PlayerRepo_SellOwned_Call struct {
	*mock.Call
}

// SellOwned is a helper method to define mock.On call
//   - ctx context.Context
//   - key domain.PlayerKey
//   - slug string
//   - price int64
func (_e *PlayerRepo_Expecter) SellOwned(ctx any, key any, slug any, price any) *PlayerRepo_SellOwned_Call {
	return &PlayerRepo_SellOwned_Call{Call: _e.mock.On("SellOwned", ctx, key, slug, price)}
}

func (_c *PlayerRepo_SellOwned_Call) Run(run func(ctx context.Context, key domain.PlayerKey, slug string, price int64)) *PlayerRepo_SellOwned_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.PlayerKey
		if args[1] != nil {
			arg1 = args[1].(domain.PlayerKey)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 int64
		if args[3] != nil {
			arg3 = args[3].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *PlayerRepo_SellOwned_Call) Return(balance int64, ok bool, err error) *PlayerRepo_SellOwned_Call {
	_c.Call.Return(balance, ok, err)
	return _c
}

func (_c *PlayerRepo_SellOwned_Call) RunAndReturn(run func(ctx context.Context, key domain.PlayerKey, slug string, price int64) (int64, bool, error)) *PlayerRepo_SellOwned_Call {
	_c.Call.Return(run)
	return _c
}

// TransferOwned provides a mock function for the type PlayerRepo
func (_mock *PlayerRepo) TransferOwned(ctx context.Context, from domain.PlayerKey, to domain.PlayerKey, slugs []string) (int64, error) {
	ret := _mock.Called(ctx, from, to, slugs)

	if len(ret) == 0 {
		panic("no return value specified for TransferOwned")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.PlayerKey, domain.PlayerKey, []string) (int64, error)); ok {
		return returnFunc(ctx, from, to, slugs)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.PlayerKey, domain.PlayerKey, []string) int64); ok {
		r0 = returnFunc(ctx, from, to, slugs)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.PlayerKey, domain.PlayerKey, []string) error); ok {
		r1 = returnFunc(ctx, from, to, slugs)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PlayerRepo_TransferOwned_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TransferOwned'
type PlayerRepo_TransferOwned_Call struct {
	*mock.Call
}

// TransferOwned is a helper method to define mock.On call
//   - ctx context.Context
//   - from domain.PlayerKey
//   - to domain.PlayerKey
//   - slugs []string
func (_e *PlayerRepo_Expecter) TransferOwned(ctx any, from any, to any, slugs any) *PlayerRepo_TransferOwned_Call {
	return &PlayerRepo_TransferOwned_Call{Call: _e.mock.On("TransferOwned", ctx, from, to, slugs)}
}

func (_c *PlayerRepo_TransferOwned_Call) Run(run func(ctx context.Context, from domain.PlayerKey, to domain.PlayerKey, slugs []string)) *PlayerRepo_TransferOwned_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.PlayerKey
		if args[1] != nil {
			arg1 = args[1].(domain.PlayerKey)
		}
		var arg2 domain.PlayerKey
		if args[2] != nil {
			arg2 = args[2].(domain.PlayerKey)
		}
		var arg3 []string
		if args[3] != nil {
			arg3 = args[3].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *PlayerRepo_TransferOwned_Call) Return(moved int64, err error) *PlayerRepo_TransferOwned_Call {
	_c.Call.Return(moved, err)
	return _c
}

func (_c *PlayerRepo_TransferOwned_Call) RunAndReturn(run func(ctx context.Context, from domain.PlayerKey, to domain.PlayerKey, slugs []string) (int64, error)) *PlayerRepo_TransferOwned_Call {
	_c.Call.Return(run)
	return _c
}
