// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	"github.com/steven-peralta/rosiebot/internal/app"
	"github.com/steven-peralta/rosiebot/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewPlayerStore creates a new instance of PlayerStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPlayerStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *PlayerStore {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &PlayerStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// PlayerStore is an autogenerated mock type for the PlayerStore type
type PlayerStore struct {
	mock.Mock
}

type PlayerStore_Expecter struct {
	mock *mock.Mock
}

func (_m *PlayerStore) EXPECT() *PlayerStore_Expecter {
	return &PlayerStore_Expecter{mock: &_m.Mock}
}

// AddOwned provides a mock function for the type PlayerStore
func (_mock *PlayerStore) AddOwned(ctx context.Context, key domain.PlayerKey, w domain.OwnedWaifu) (bool, error) {
	ret := _mock.Called(ctx, key, w)

	if len(ret) == 0 {
		panic("no return value specified for AddOwned")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.PlayerKey, domain.OwnedWaifu) (bool, error)); ok {
		return returnFunc(ctx, key, w)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.PlayerKey, domain.OwnedWaifu) bool); ok {
		r0 = returnFunc(ctx, key, w)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.PlayerKey, domain.OwnedWaifu) error); ok {
		r1 = returnFunc(ctx, key, w)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PlayerStore_AddOwned_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddOwned'
type PlayerStore_AddOwned_Call struct {
	*mock.Call
}

// AddOwned is a helper method to define mock.On call
//   - ctx context.Context
//   - key domain.PlayerKey
//   - w domain.OwnedWaifu
func (_e *PlayerStore_Expecter) AddOwned(ctx any, key any, w any) *PlayerStore_AddOwned_Call {
	return &PlayerStore_AddOwned_Call{Call: _e.mock.On("AddOwned", ctx, key, w)}
}

func (_c *PlayerStore_AddOwned_Call) Run(run func(ctx context.Context, key domain.PlayerKey, w domain.OwnedWaifu)) *PlayerStore_AddOwned_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.PlayerKey
		if args[1] != nil {
			arg1 = args[1].(domain.PlayerKey)
		}
		var arg2 domain.OwnedWaifu
		if args[2] != nil {
			arg2 = args[2].(domain.OwnedWaifu)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *PlayerStore_AddOwned_Call) Return(inserted bool, err error) *PlayerStore_AddOwned_Call {
	_c.Call.Return(inserted, err)
	return _c
}

func (_c *PlayerStore_AddOwned_Call) RunAndReturn(run func(ctx context.Context, key domain.PlayerKey, w domain.OwnedWaifu) (bool, error)) *PlayerStore_AddOwned_Call {
	_c.Call.Return(run)
	return _c
}

// AdjustCoins provides a mock function for the type PlayerStore
func (_mock *PlayerStore) AdjustCoins(ctx context.Context, key domain.PlayerKey, delta int64) (int64, bool, error) {
	ret := _mock.Called(ctx, key, delta)

	if len(ret) == 0 {
		panic("no return value specified for AdjustCoins")
	}

	var r0 int64
	var r1 bool
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.PlayerKey, int64) (int64, bool, error)); ok {
		return returnFunc(ctx, key, delta)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.PlayerKey, int64) int64); ok {
		r0 = returnFunc(ctx, key, delta)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.PlayerKey, int64) bool); ok {
		r1 = returnFunc(ctx, key, delta)
	} else {
		r1 = ret.Get(1).(bool)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, domain.PlayerKey, int64) error); ok {
		r2 = returnFunc(ctx, key, delta)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// PlayerStore_AdjustCoins_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AdjustCoins'
type PlayerStore_AdjustCoins_Call struct {
	*mock.Call
}

// AdjustCoins is a helper method to define mock.On call
//   - ctx context.Context
//   - key domain.PlayerKey
//   - delta int64
func (_e *PlayerStore_Expecter) AdjustCoins(ctx any, key any, delta any) *PlayerStore_AdjustCoins_Call {
	return &PlayerStore_AdjustCoins_Call{Call: _e.mock.On("AdjustCoins", ctx, key, delta)}
}

func (_c *PlayerStore_AdjustCoins_Call) Run(run func(ctx context.Context, key domain.PlayerKey, delta int64)) *PlayerStore_AdjustCoins_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.PlayerKey
		if args[1] != nil {
			arg1 = args[1].(domain.PlayerKey)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *PlayerStore_AdjustCoins_Call) Return(balance int64, ok bool, err error) *PlayerStore_AdjustCoins_Call {
	_c.Call.Return(balance, ok, err)
	return _c
}

func (_c *PlayerStore_AdjustCoins_Call) RunAndReturn(run func(ctx context.Context, key domain.PlayerKey, delta int64) (int64, bool, error)) *PlayerStore_AdjustCoins_Call {
	_c.Call.Return(run)
	return _c
}

// ClaimDaily provides a mock function for the type PlayerStore
func (_mock *PlayerStore) ClaimDaily(ctx context.Context, key domain.PlayerKey, amount int64, windowStart time.Time, now time.Time) (int64, bool, error) {
	ret := _mock.Called(ctx, key, amount, windowStart, now)

	if len(ret) == 0 {
		panic("no return value specified for ClaimDaily")
	}

	var r0 int64
	var r1 bool
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.PlayerKey, int64, time.Time, time.Time) (int64, bool, error)); ok {
		return returnFunc(ctx, key, amount, windowStart, now)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.PlayerKey, int64, time.Time, time.Time) int64); ok {
		r0 = returnFunc(ctx, key, amount, windowStart, now)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.PlayerKey, int64, time.Time, time.Time) bool); ok {
		r1 = returnFunc(ctx, key, amount, windowStart, now)
	} else {
		r1 = ret.Get(1).(bool)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, domain.PlayerKey, int64, time.Time, time.Time) error); ok {
		r2 = returnFunc(ctx, key, amount, windowStart, now)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// PlayerStore_ClaimDaily_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClaimDaily'
type PlayerStore_ClaimDaily_Call struct {
	*mock.Call
}

// ClaimDaily is a helper method to define mock.On call
//   - ctx context.Context
//   - key domain.PlayerKey
//   - amount int64
//   - windowStart time.Time
//   - now time.Time
func (_e *PlayerStore_Expecter) ClaimDaily(ctx any, key any, amount any, windowStart any, now any) *PlayerStore_ClaimDaily_Call {
	return &PlayerStore_ClaimDaily_Call{Call: _e.mock.On("ClaimDaily", ctx, key, amount, windowStart, now)}
}

func (_c *PlayerStore_ClaimDaily_Call) Run(run func(ctx context.Context, key domain.PlayerKey, amount int64, windowStart time.Time, now time.Time)) *PlayerStore_ClaimDaily_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.PlayerKey
		if args[1] != nil {
			arg1 = args[1].(domain.PlayerKey)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		var arg4 time.Time
		if args[4] != nil {
			arg4 = args[4].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *PlayerStore_ClaimDaily_Call) Return(balance int64, ok bool, err error) *PlayerStore_ClaimDaily_Call {
	_c.Call.Return(balance, ok, err)
	return _c
}

func (_c *PlayerStore_ClaimDaily_Call) RunAndReturn(run func(ctx context.Context, key domain.PlayerKey, amount int64, windowStart time.Time, now time.Time) (int64, bool, error)) *PlayerStore_ClaimDaily_Call {
	_c.Call.Return(run)
	return _c
}

// CountOwned provides a mock function for the type PlayerStore
func (_mock *PlayerStore) CountOwned(ctx context.Context, key domain.PlayerKey) (int, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for CountOwned")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.PlayerKey) (int, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.PlayerKey) int); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.PlayerKey) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PlayerStore_CountOwned_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountOwned'
type PlayerStore_CountOwned_Call struct {
	*mock.Call
}

// CountOwned is a helper method to define mock.On call
//   - ctx context.Context
//   - key domain.PlayerKey
func (_e *PlayerStore_Expecter) CountOwned(ctx any, key any) *PlayerStore_CountOwned_Call {
	return &PlayerStore_CountOwned_Call{Call: _e.mock.On("CountOwned", ctx, key)}
}

func (_c *PlayerStore_CountOwned_Call) Run(run func(ctx context.Context, key domain.PlayerKey)) *PlayerStore_CountOwned_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.PlayerKey
		if args[1] != nil {
			arg1 = args[1].(domain.PlayerKey)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *PlayerStore_CountOwned_Call) Return(n int, err error) *PlayerStore_CountOwned_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *PlayerStore_CountOwned_Call) RunAndReturn(run func(ctx context.Context, key domain.PlayerKey) (int, error)) *PlayerStore_CountOwned_Call {
	_c.Call.Return(run)
	return _c
}

// CountRolls provides a mock function for the type PlayerStore
func (_mock *PlayerStore) CountRolls(ctx context.Context, key domain.PlayerKey) (int, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for CountRolls")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.PlayerKey) (int, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.PlayerKey) int); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.PlayerKey) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PlayerStore_CountRolls_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountRolls'
type PlayerStore_CountRolls_Call struct {
	*mock.Call
}

// CountRolls is a helper method to define mock.On call
//   - ctx context.Context
//   - key domain.PlayerKey
func (_e *PlayerStore_Expecter) CountRolls(ctx any, key any) *PlayerStore_CountRolls_Call {
	return &PlayerStore_CountRolls_Call{Call: _e.mock.On("CountRolls", ctx, key)}
}

func (_c *PlayerStore_CountRolls_Call) Run(run func(ctx context.Context, key domain.PlayerKey)) *PlayerStore_CountRolls_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.PlayerKey
		if args[1] != nil {
			arg1 = args[1].(domain.PlayerKey)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *PlayerStore_CountRolls_Call) Return(n int, err error) *PlayerStore_CountRolls_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *PlayerStore_CountRolls_Call) RunAndReturn(run func(ctx context.Context, key domain.PlayerKey) (int, error)) *PlayerStore_CountRolls_Call {
	_c.Call.Return(run)
	return _c
}

// DebitCoins provides a mock function for the type PlayerStore
func (_mock *PlayerStore) DebitCoins(ctx context.Context, key domain.PlayerKey, amount int64) (int64, bool, error) {
	ret := _mock.Called(ctx, key, amount)

	if len(ret) == 0 {
		panic("no return value specified for DebitCoins")
	}

	var r0 int64
	var r1 bool
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.PlayerKey, int64) (int64, bool, error)); ok {
		return returnFunc(ctx, key, amount)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.PlayerKey, int64) int64); ok {
		r0 = returnFunc(ctx, key, amount)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.PlayerKey, int64) bool); ok {
		r1 = returnFunc(ctx, key, amount)
	} else {
		r1 = ret.Get(1).(bool)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, domain.PlayerKey, int64) error); ok {
		r2 = returnFunc(ctx, key, amount)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// PlayerStore_DebitCoins_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DebitCoins'
type PlayerStore_DebitCoins_Call struct {
	*mock.Call
}

// DebitCoins is a helper method to define mock.On call
//   - ctx context.Context
//   - key domain.PlayerKey
//   - amount int64
func (_e *PlayerStore_Expecter) DebitCoins(ctx any, key any, amount any) *PlayerStore_DebitCoins_Call {
	return &PlayerStore_DebitCoins_Call{Call: _e.mock.On("DebitCoins", ctx, key, amount)}
}

func (_c *PlayerStore_DebitCoins_Call) Run(run func(ctx context.Context, key domain.PlayerKey, amount int64)) *PlayerStore_DebitCoins_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.PlayerKey
		if args[1] != nil {
			arg1 = args[1].(domain.PlayerKey)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *PlayerStore_DebitCoins_Call) Return(balance int64, ok bool, err error) *PlayerStore_DebitCoins_Call {
	_c.Call.Return(balance, ok, err)
	return _c
}

func (_c *PlayerStore_DebitCoins_Call) RunAndReturn(run func(ctx context.Context, key domain.PlayerKey, amount int64) (int64, bool, error)) *PlayerStore_DebitCoins_Call {
	_c.Call.Return(run)
	return _c
}

// EnsurePlayer provides a mock function for the type PlayerStore
func (_mock *PlayerStore) EnsurePlayer(ctx context.Context, key domain.PlayerKey) (domain.Player, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for EnsurePlayer")
	}

	var r0 domain.Player
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.PlayerKey) (domain.Player, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.PlayerKey) domain.Player); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Get(0).(domain.Player)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.PlayerKey) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PlayerStore_EnsurePlayer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnsurePlayer'
type PlayerStore_EnsurePlayer_Call struct {
	*mock.Call
}

// EnsurePlayer is a helper method to define mock.On call
//   - ctx context.Context
//   - key domain.PlayerKey
func (_e *PlayerStore_Expecter) EnsurePlayer(ctx any, key any) *PlayerStore_EnsurePlayer_Call {
	return &PlayerStore_EnsurePlayer_Call{Call: _e.mock.On("EnsurePlayer", ctx, key)}
}

func (_c *PlayerStore_EnsurePlayer_Call) Run(run func(ctx context.Context, key domain.PlayerKey)) *PlayerStore_EnsurePlayer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.PlayerKey
		if args[1] != nil {
			arg1 = args[1].(domain.PlayerKey)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *PlayerStore_EnsurePlayer_Call) Return(player domain.Player, err error) *PlayerStore_EnsurePlayer_Call {
	_c.Call.Return(player, err)
	return _c
}

func (_c *PlayerStore_EnsurePlayer_Call) RunAndReturn(run func(ctx context.Context, key domain.PlayerKey) (domain.Player, error)) *PlayerStore_EnsurePlayer_Call {
	_c.Call.Return(run)
	return _c
}

// GetOwned provides a mock function for the type PlayerStore
func (_mock *PlayerStore) GetOwned(ctx context.Context, key domain.PlayerKey, slug string) (domain.OwnedWaifu, error) {
	ret := _mock.Called(ctx, key, slug)

	if len(ret) == 0 {
		panic("no return value specified for GetOwned")
	}

	var r0 domain.OwnedWaifu
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.PlayerKey, string) (domain.OwnedWaifu, error)); ok {
		return returnFunc(ctx, key, slug)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.PlayerKey, string) domain.OwnedWaifu); ok {
		r0 = returnFunc(ctx, key, slug)
	} else {
		r0 = ret.Get(0).(domain.OwnedWaifu)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.PlayerKey, string) error); ok {
		r1 = returnFunc(ctx, key, slug)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PlayerStore_GetOwned_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOwned'
type PlayerStore_GetOwned_Call struct {
	*mock.Call
}

// GetOwned is a helper method to define mock.On call
//   - ctx context.Context
//   - key domain.PlayerKey
//   - slug string
func (_e *PlayerStore_Expecter) GetOwned(ctx any, key any, slug any) *PlayerStore_GetOwned_Call {
	return &PlayerStore_GetOwned_Call{Call: _e.mock.On("GetOwned", ctx, key, slug)}
}

func (_c *PlayerStore_GetOwned_Call) Run(run func(ctx context.Context, key domain.PlayerKey, slug string)) *PlayerStore_GetOwned_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.PlayerKey
		if args[1] != nil {
			arg1 = args[1].(domain.PlayerKey)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *PlayerStore_GetOwned_Call) Return(ownedWaifu domain.OwnedWaifu, err error) *PlayerStore_GetOwned_Call {
	_c.Call.Return(ownedWaifu, err)
	return _c
}

func (_c *PlayerStore_GetOwned_Call) RunAndReturn(run func(ctx context.Context, key domain.PlayerKey, slug string) (domain.OwnedWaifu, error)) *PlayerStore_GetOwned_Call {
	_c.Call.Return(run)
	return _c
}

// GetPlayer provides a mock function for the type PlayerStore
func (_mock *PlayerStore) GetPlayer(ctx context.Context, key domain.PlayerKey) (domain.Player, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for GetPlayer")
	}

	var r0 domain.Player
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.PlayerKey) (domain.Player, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.PlayerKey) domain.Player); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Get(0).(domain.Player)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.PlayerKey) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PlayerStore_GetPlayer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPlayer'
type PlayerStore_GetPlayer_Call struct {
	*mock.Call
}

// GetPlayer is a helper method to define mock.On call
//   - ctx context.Context
//   - key domain.PlayerKey
func (_e *PlayerStore_Expecter) GetPlayer(ctx any, key any) *PlayerStore_GetPlayer_Call {
	return &PlayerStore_GetPlayer_Call{Call: _e.mock.On("GetPlayer", ctx, key)}
}

func (_c *PlayerStore_GetPlayer_Call) Run(run func(ctx context.Context, key domain.PlayerKey)) *PlayerStore_GetPlayer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.PlayerKey
		if args[1] != nil {
			arg1 = args[1].(domain.PlayerKey)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *PlayerStore_GetPlayer_Call) Return(player domain.Player, err error) *PlayerStore_GetPlayer_Call {
	_c.Call.Return(player, err)
	return _c
}

func (_c *PlayerStore_GetPlayer_Call) RunAndReturn(run func(ctx context.Context, key domain.PlayerKey) (domain.Player, error)) *PlayerStore_GetPlayer_Call {
	_c.Call.Return(run)
	return _c
}

// GuildInventory provides a mock function for the type PlayerStore
func (_mock *PlayerStore) GuildInventory(ctx context.Context, guildID string) ([]app.OwnedRow, error) {
	ret := _mock.Called(ctx, guildID)

	if len(ret) == 0 {
		panic("no return value specified for GuildInventory")
	}

	var r0 []app.OwnedRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]app.OwnedRow, error)); ok {
		return returnFunc(ctx, guildID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []app.OwnedRow); ok {
		r0 = returnFunc(ctx, guildID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]app.OwnedRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, guildID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PlayerStore_GuildInventory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GuildInventory'
type PlayerStore_GuildInventory_Call struct {
	*mock.Call
}

// GuildInventory is a helper method to define mock.On call
//   - ctx context.Context
//   - guildID string
func (_e *PlayerStore_Expecter) GuildInventory(ctx any, guildID any) *PlayerStore_GuildInventory_Call {
	return &PlayerStore_GuildInventory_Call{Call: _e.mock.On("GuildInventory", ctx, guildID)}
}

func (_c *PlayerStore_GuildInventory_Call) Run(run func(ctx context.Context, guildID string)) *PlayerStore_GuildInventory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *PlayerStore_GuildInventory_Call) Return(ownedRows []app.OwnedRow, err error) *PlayerStore_GuildInventory_Call {
	_c.Call.Return(ownedRows, err)
	return _c
}

func (_c *PlayerStore_GuildInventory_Call) RunAndReturn(run func(ctx context.Context, guildID string) ([]app.OwnedRow, error)) *PlayerStore_GuildInventory_Call {
	_c.Call.Return(run)
	return _c
}

// GuildPlayers provides a mock function for the type PlayerStore
func (_mock *PlayerStore) GuildPlayers(ctx context.Context, guildID string) ([]domain.Player, error) {
	ret := _mock.Called(ctx, guildID)

	if len(ret) == 0 {
		panic("no return value specified for GuildPlayers")
	}

	var r0 []domain.Player
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]domain.Player, error)); ok {
		return returnFunc(ctx, guildID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []domain.Player); ok {
		r0 = returnFunc(ctx, guildID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Player)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, guildID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PlayerStore_GuildPlayers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GuildPlayers'
type PlayerStore_GuildPlayers_Call struct {
	*mock.Call
}

// GuildPlayers is a helper method to define mock.On call
//   - ctx context.Context
//   - guildID string
func (_e *PlayerStore_Expecter) GuildPlayers(ctx any, guildID any) *PlayerStore_GuildPlayers_Call {
	return &PlayerStore_GuildPlayers_Call{Call: _e.mock.On("GuildPlayers", ctx, guildID)}
}

func (_c *PlayerStore_GuildPlayers_Call) Run(run func(ctx context.Context, guildID string)) *PlayerStore_GuildPlayers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *PlayerStore_GuildPlayers_Call) Return(players []domain.Player, err error) *PlayerStore_GuildPlayers_Call {
	_c.Call.Return(players, err)
	return _c
}

func (_c *PlayerStore_GuildPlayers_Call) RunAndReturn(run func(ctx context.Context, guildID string) ([]domain.Player, error)) *PlayerStore_GuildPlayers_Call {
	_c.Call.Return(run)
	return _c
}

// ListOwned provides a mock function for the type PlayerStore
func (_mock *PlayerStore) ListOwned(ctx context.Context, key domain.PlayerKey, prefix string, limit int) ([]domain.OwnedWaifu, error) {
	ret := _mock.Called(ctx, key, prefix, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListOwned")
	}

	var r0 []domain.OwnedWaifu
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.PlayerKey, string, int) ([]domain.OwnedWaifu, error)); ok {
		return returnFunc(ctx, key, prefix, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.PlayerKey, string, int) []domain.OwnedWaifu); ok {
		r0 = returnFunc(ctx, key, prefix, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.OwnedWaifu)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.PlayerKey, string, int) error); ok {
		r1 = returnFunc(ctx, key, prefix, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PlayerStore_ListOwned_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListOwned'
type PlayerStore_ListOwned_Call struct {
	*mock.Call
}

// ListOwned is a helper method to define mock.On call
//   - ctx context.Context
//   - key domain.PlayerKey
//   - prefix string
//   - limit int
func (_e *PlayerStore_Expecter) ListOwned(ctx any, key any, prefix any, limit any) *PlayerStore_ListOwned_Call {
	return &PlayerStore_ListOwned_Call{Call: _e.mock.On("ListOwned", ctx, key, prefix, limit)}
}

func (_c *PlayerStore_ListOwned_Call) Run(run func(ctx context.Context, key domain.PlayerKey, prefix string, limit int)) *PlayerStore_ListOwned_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.PlayerKey
		if args[1] != nil {
			arg1 = args[1].(domain.PlayerKey)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *PlayerStore_ListOwned_Call) Return(ownedWaifus []domain.OwnedWaifu, err error) *PlayerStore_ListOwned_Call {
	_c.Call.Return(ownedWaifus, err)
	return _c
}

func (_c *PlayerStore_ListOwned_Call) RunAndReturn(run func(ctx context.Context, key domain.PlayerKey, prefix string, limit int) ([]domain.OwnedWaifu, error)) *PlayerStore_ListOwned_Call {
	_c.Call.Return(run)
	return _c
}

// LockPlayers provides a mock function for the type PlayerStore
func (_mock *PlayerStore) LockPlayers(ctx context.Context, keys ...domain.PlayerKey) ([]domain.Player, error) {
	var tmpRet mock.Arguments
	if len(keys) > 0 {
		tmpRet = _mock.Called(ctx, keys)
	} else {
		tmpRet = _mock.Called(ctx)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for LockPlayers")
	}

	var r0 []domain.Player
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...domain.PlayerKey) ([]domain.Player, error)); ok {
		return returnFunc(ctx, keys...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...domain.PlayerKey) []domain.Player); ok {
		r0 = returnFunc(ctx, keys...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Player)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ...domain.PlayerKey) error); ok {
		r1 = returnFunc(ctx, keys...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PlayerStore_LockPlayers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LockPlayers'
type PlayerStore_LockPlayers_Call struct {
	*mock.Call
}

// LockPlayers is a helper method to define mock.On call
//   - ctx context.Context
//   - keys ...domain.PlayerKey
func (_e *PlayerStore_Expecter) LockPlayers(ctx any, keys ...any) *PlayerStore_LockPlayers_Call {
	return &PlayerStore_LockPlayers_Call{Call: _e.mock.On("LockPlayers",
		append([]any{ctx}, keys...)...)}
}

func (_c *PlayerStore_LockPlayers_Call) Run(run func(ctx context.Context, keys ...domain.PlayerKey)) *PlayerStore_LockPlayers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []domain.PlayerKey
		var variadicArgs []domain.PlayerKey
		if len(args) > 1 {
			variadicArgs = args[1].([]domain.PlayerKey)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *PlayerStore_LockPlayers_Call) Return(players []domain.Player, err error) *PlayerStore_LockPlayers_Call {
	_c.Call.Return(players, err)
	return _c
}

func (_c *PlayerStore_LockPlayers_Call) RunAndReturn(run func(ctx context.Context, keys ...domain.PlayerKey) ([]domain.Player, error)) *PlayerStore_LockPlayers_Call {
	_c.Call.Return(run)
	return _c
}

// OwnedSlugs provides a mock function for the type PlayerStore
func (_mock *PlayerStore) OwnedSlugs(ctx context.Context, key domain.PlayerKey, slugs []string) ([]string, error) {
	ret := _mock.Called(ctx, key, slugs)

	if len(ret) == 0 {
		panic("no return value specified for OwnedSlugs")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.PlayerKey, []string) ([]string, error)); ok {
		return returnFunc(ctx, key, slugs)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.PlayerKey, []string) []string); ok {
		r0 = returnFunc(ctx, key, slugs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.PlayerKey, []string) error); ok {
		r1 = returnFunc(ctx, key, slugs)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PlayerStore_OwnedSlugs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OwnedSlugs'
type PlayerStore_OwnedSlugs_Call struct {
	*mock.Call
}

// OwnedSlugs is a helper method to define mock.On call
//   - ctx context.Context
//   - key domain.PlayerKey
//   - slugs []string
func (_e *PlayerStore_Expecter) OwnedSlugs(ctx any, key any, slugs any) *PlayerStore_OwnedSlugs_Call {
	return &PlayerStore_OwnedSlugs_Call{Call: _e.mock.On("OwnedSlugs", ctx, key, slugs)}
}

func (_c *PlayerStore_OwnedSlugs_Call) Run(run func(ctx context.Context, key domain.PlayerKey, slugs []string)) *PlayerStore_OwnedSlugs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.PlayerKey
		if args[1] != nil {
			arg1 = args[1].(domain.PlayerKey)
		}
		var arg2 []string
		if args[2] != nil {
			arg2 = args[2].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *PlayerStore_OwnedSlugs_Call) Return(strings []string, err error) *PlayerStore_OwnedSlugs_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *PlayerStore_OwnedSlugs_Call) RunAndReturn(run func(ctx context.Context, key domain.PlayerKey, slugs []string) ([]string, error)) *PlayerStore_OwnedSlugs_Call {
	_c.Call.Return(run)
	return _c
}

// RecentRolls provides a mock function for the type PlayerStore
func (_mock *PlayerStore) RecentRolls(ctx context.Context, key domain.PlayerKey, limit int) ([]domain.RollRecord, error) {
	ret := _mock.Called(ctx, key, limit)

	if len(ret) == 0 {
		panic("no return value specified for RecentRolls")
	}

	var r0 []domain.RollRecord
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.PlayerKey, int) ([]domain.RollRecord, error)); ok {
		return returnFunc(ctx, key, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.PlayerKey, int) []domain.RollRecord); ok {
		r0 = returnFunc(ctx, key, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.RollRecord)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.PlayerKey, int) error); ok {
		r1 = returnFunc(ctx, key, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PlayerStore_RecentRolls_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecentRolls'
type PlayerStore_RecentRolls_Call struct {
	*mock.Call
}

// RecentRolls is a helper method to define mock.On call
//   - ctx context.Context
//   - key domain.PlayerKey
//   - limit int
func (_e *PlayerStore_Expecter) RecentRolls(ctx any, key any, limit any) *PlayerStore_RecentRolls_Call {
	return &PlayerStore_RecentRolls_Call{Call: _e.mock.On("RecentRolls", ctx, key, limit)}
}

func (_c *PlayerStore_RecentRolls_Call) Run(run func(ctx context.Context, key domain.PlayerKey, limit int)) *PlayerStore_RecentRolls_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.PlayerKey
		if args[1] != nil {
			arg1 = args[1].(domain.PlayerKey)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *PlayerStore_RecentRolls_Call) Return(rollRecords []domain.RollRecord, err error) *PlayerStore_RecentRolls_Call {
	_c.Call.Return(rollRecords, err)
	return _c
}

func (_c *PlayerStore_RecentRolls_Call) RunAndReturn(run func(ctx context.Context, key domain.PlayerKey, limit int) ([]domain.RollRecord, error)) *PlayerStore_RecentRolls_Call {
	_c.Call.Return(run)
	return _c
}

// RecordRoll provides a mock function for the type PlayerStore
func (_mock *PlayerStore) RecordRoll(ctx context.Context, key domain.PlayerKey, r domain.RollRecord) error {
	ret := _mock.Called(ctx, key, r)

	if len(ret) == 0 {
		panic("no return value specified for RecordRoll")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.PlayerKey, domain.RollRecord) error); ok {
		r0 = returnFunc(ctx, key, r)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// PlayerStore_RecordRoll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordRoll'
type PlayerStore_RecordRoll_Call struct {
	*mock.Call
}

// RecordRoll is a helper method to define mock.On call
//   - ctx context.Context
//   - key domain.PlayerKey
//   - r domain.RollRecord
func (_e *PlayerStore_Expecter) RecordRoll(ctx any, key any, r any) *PlayerStore_RecordRoll_Call {
	return &PlayerStore_RecordRoll_Call{Call: _e.mock.On("RecordRoll", ctx, key, r)}
}

func (_c *PlayerStore_RecordRoll_Call) Run(run func(ctx context.Context, key domain.PlayerKey, r domain.RollRecord)) *PlayerStore_RecordRoll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.PlayerKey
		if args[1] != nil {
			arg1 = args[1].(domain.PlayerKey)
		}
		var arg2 domain.RollRecord
		if args[2] != nil {
			arg2 = args[2].(domain.RollRecord)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *PlayerStore_RecordRoll_Call) Return(err error) *PlayerStore_RecordRoll_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *PlayerStore_RecordRoll_Call) RunAndReturn(run func(ctx context.Context, key domain.PlayerKey, r domain.RollRecord) error) *PlayerStore_RecordRoll_Call {
	_c.Call.Return(run)
	return _c
}

// SellOwned provides a mock function for the type PlayerStore
func (_mock *PlayerStore) SellOwned(ctx context.Context, key domain.PlayerKey, slug string, price int64) (int64, bool, error) {
	ret := _mock.Called(ctx, key, slug, price)

	if len(ret) == 0 {
		panic("no return value specified for SellOwned")
	}

	var r0 int64
	var r1 bool
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.PlayerKey, string, int64) (int64, bool, error)); ok {
		return returnFunc(ctx, key, slug, price)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.PlayerKey, string, int64) int64); ok {
		r0 = returnFunc(ctx, key, slug, price)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.PlayerKey, string, int64) bool); ok {
		r1 = returnFunc(ctx, key, slug, price)
	} else {
		r1 = ret.Get(1).(bool)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, domain.PlayerKey, string, int64) error); ok {
		r2 = returnFunc(ctx, key, slug, price)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// PlayerStore_SellOwned_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SellOwned'
type PlayerStore_SellOwned_Call struct {
	*mock.Call
}

// SellOwned is a helper method to define mock.On call
//   - ctx context.Context
//   - key domain.PlayerKey
//   - slug string
//   - price int64
func (_e *PlayerStore_Expecter) SellOwned(ctx any, key any, slug any, price any) *PlayerStore_SellOwned_Call {
	return &PlayerStore_SellOwned_Call{Call: _e.mock.On("SellOwned", ctx, key, slug, price)}
}

func (_c *PlayerStore_SellOwned_Call) Run(run func(ctx context.Context, key domain.PlayerKey, slug string, price int64)) *PlayerStore_SellOwned_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.PlayerKey
		if args[1] != nil {
			arg1 = args[1].(domain.PlayerKey)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 int64
		if args[3] != nil {
			arg3 = args[3].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *PlayerStore_SellOwned_Call) Return(balance int64, ok bool, err error) *PlayerStore_SellOwned_Call {
	_c.Call.Return(balance, ok, err)
	return _c
}

func (_c *PlayerStore_SellOwned_Call) RunAndReturn(run func(ctx context.Context, key domain.PlayerKey, slug string, price int64) (int64, bool, error)) *PlayerStore_SellOwned_Call {
	_c.Call.Return(run)
	return _c
}

// SetCoins provides a mock function for the type PlayerStore
func (_mock *PlayerStore) SetCoins(ctx context.Context, key domain.PlayerKey, coins int64) (int64, error) {
	ret := _mock.Called(ctx, key, coins)

	if len(ret) == 0 {
		panic("no return value specified for SetCoins")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.PlayerKey, int64) (int64, error)); ok {
		return returnFunc(ctx, key, coins)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.PlayerKey, int64) int64); ok {
		r0 = returnFunc(ctx, key, coins)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.PlayerKey, int64) error); ok {
		r1 = returnFunc(ctx, key, coins)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PlayerStore_SetCoins_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetCoins'
type PlayerStore_SetCoins_Call struct {
	*mock.Call
}

// SetCoins is a helper method to define mock.On call
//   - ctx context.Context
//   - key domain.PlayerKey
//   - coins int64
func (_e *PlayerStore_Expecter) SetCoins(ctx any, key any, coins any) *PlayerStore_SetCoins_Call {
	return &PlayerStore_SetCoins_Call{Call: _e.mock.On("SetCoins", ctx, key, coins)}
}

func (_c *PlayerStore_SetCoins_Call) Run(run func(ctx context.Context, key domain.PlayerKey, coins int64)) *PlayerStore_SetCoins_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.PlayerKey
		if args[1] != nil {
			arg1 = args[1].(domain.PlayerKey)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *PlayerStore_SetCoins_Call) Return(balance int64, err error) *PlayerStore_SetCoins_Call {
	_c.Call.Return(balance, err)
	return _c
}

func (_c *PlayerStore_SetCoins_Call) RunAndReturn(run func(ctx context.Context, key domain.PlayerKey, coins int64) (int64, error)) *PlayerStore_SetCoins_Call {
	_c.Call.Return(run)
	return _c
}

// TransferOwned provides a mock function for the type PlayerStore
func (_mock *PlayerStore) TransferOwned(ctx context.Context, from domain.PlayerKey, to domain.PlayerKey, slugs []string) (int64, error) {
	ret := _mock.Called(ctx, from, to, slugs)

	if len(ret) == 0 {
		panic("no return value specified for TransferOwned")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.PlayerKey, domain.PlayerKey, []string) (int64, error)); ok {
		return returnFunc(ctx, from, to, slugs)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.PlayerKey, domain.PlayerKey, []string) int64); ok {
		r0 = returnFunc(ctx, from, to, slugs)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.PlayerKey, domain.PlayerKey, []string) error); ok {
		r1 = returnFunc(ctx, from, to, slugs)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PlayerStore_TransferOwned_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TransferOwned'
type PlayerStore_TransferOwned_Call struct {
	*mock.Call
}

// TransferOwned is a helper method to define mock.On call
//   - ctx context.Context
//   - from domain.PlayerKey
//   - to domain.PlayerKey
//   - slugs []string
func (_e *PlayerStore_Expecter) TransferOwned(ctx any, from any, to any, slugs any) *PlayerStore_TransferOwned_Call {
	return &PlayerStore_TransferOwned_Call{Call: _e.mock.On("TransferOwned", ctx, from, to, slugs)}
}

func (_c *PlayerStore_TransferOwned_Call) Run(run func(ctx context.Context, from domain.PlayerKey, to domain.PlayerKey, slugs []string)) *PlayerStore_TransferOwned_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.PlayerKey
		if args[1] != nil {
			arg1 = args[1].(domain.PlayerKey)
		}
		var arg2 domain.PlayerKey
		if args[2] != nil {
			arg2 = args[2].(domain.PlayerKey)
		}
		var arg3 []string
		if args[3] != nil {
			arg3 = args[3].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *PlayerStore_TransferOwned_Call) Return(moved int64, err error) *PlayerStore_TransferOwned_Call {
	_c.Call.Return(moved, err)
	return _c
}

func (_c *PlayerStore_TransferOwned_Call) RunAndReturn(run func(ctx context.Context, from domain.PlayerKey, to domain.PlayerKey, slugs []string) (int64, error)) *PlayerStore_TransferOwned_Call {
	_c.Call.Return(run)
	return _c
}

// WithinTx provides a mock function for the type PlayerStore
func (_mock *PlayerStore) WithinTx(ctx context.Context, fn func(app.PlayerRepo) error) error {
	ret := _mock.Called(ctx, fn)

	if len(ret) == 0 {
		panic("no return value specified for WithinTx")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, func(app.PlayerRepo) error) error); ok {
		r0 = returnFunc(ctx, fn)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// PlayerStore_WithinTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithinTx'
type PlayerStore_WithinTx_Call struct {
	*mock.Call
}

// WithinTx is a helper method to define mock.On call
//   - ctx context.Context
//   - fn func(app.PlayerRepo) error
func (_e *PlayerStore_Expecter) WithinTx(ctx any, fn any) *PlayerStore_WithinTx_Call {
	return &PlayerStore_WithinTx_Call{Call: _e.mock.On("WithinTx", ctx, fn)}
}

func (_c *PlayerStore_WithinTx_Call) Run(run func(ctx context.Context, fn func(app.PlayerRepo) error)) *PlayerStore_WithinTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 func(app.PlayerRepo) error
		if args[1] != nil {
			arg1 = args[1].(func(app.PlayerRepo) error)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *PlayerStore_WithinTx_Call) Return(err error) *PlayerStore_WithinTx_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *PlayerStore_WithinTx_Call) RunAndReturn(run func(ctx context.Context, fn func(app.PlayerRepo) error) error) *PlayerStore_WithinTx_Call {
	_c.Call.Return(run)
	return _c
}
