// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewRandom creates a new instance of Random. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRandom(t interface {
	mock.TestingT
	Cleanup(func())
}) *Random {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &Random{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// Random is an autogenerated mock type for the Random type
type Random struct {
	mock.Mock
}

type Random_Expecter struct {
	mock *mock.Mock
}

func (_m *Random) EXPECT() *Random_Expecter {
	return &Random_Expecter{mock: &_m.Mock}
}

// IntN provides a mock function for the type Random
func (_mock *Random) IntN(n int) int {
	ret := _mock.Called(n)

	if len(ret) == 0 {
		panic("no return value specified for IntN")
	}

	var r0 int
	if returnFunc, ok := ret.Get(0).(func(int) int); ok {
		r0 = returnFunc(n)
	} else {
		r0 = ret.Get(0).(int)
	}
	return r0
}

// Random_IntN_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IntN'
type Random_IntN_Call struct {
	*mock.Call
}

// IntN is a helper method to define mock.On call
//   - n int
func (_e *Random_Expecter) IntN(n any) *Random_IntN_Call {
	return &Random_IntN_Call{Call: _e.mock.On("IntN", n)}
}

func (_c *Random_IntN_Call) Run(run func(n int)) *Random_IntN_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Random_IntN_Call) Return(n1 int) *Random_IntN_Call {
	_c.Call.Return(n1)
	return _c
}

func (_c *Random_IntN_Call) RunAndReturn(run func(n int) int) *Random_IntN_Call {
	_c.Call.Return(run)
	return _c
}
