// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/steven-peralta/rosiebot/internal/app"
	mock "github.com/stretchr/testify/mock"
)

// NewRankingStatusProvider creates a new instance of RankingStatusProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRankingStatusProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *RankingStatusProvider {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &RankingStatusProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// RankingStatusProvider is an autogenerated mock type for the RankingStatusProvider type
type RankingStatusProvider struct {
	mock.Mock
}

type RankingStatusProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *RankingStatusProvider) EXPECT() *RankingStatusProvider_Expecter {
	return &RankingStatusProvider_Expecter{mock: &_m.Mock}
}

// Status provides a mock function for the type RankingStatusProvider
func (_mock *RankingStatusProvider) Status() app.RankingStatus {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Status")
	}

	var r0 app.RankingStatus
	if returnFunc, ok := ret.Get(0).(func() app.RankingStatus); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(app.RankingStatus)
	}
	return r0
}

// RankingStatusProvider_Status_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Status'
type RankingStatusProvider_Status_Call struct {
	*mock.Call
}

// Status is a helper method to define mock.On call
func (_e *RankingStatusProvider_Expecter) Status() *RankingStatusProvider_Status_Call {
	return &RankingStatusProvider_Status_Call{Call: _e.mock.On("Status")}
}

func (_c *RankingStatusProvider_Status_Call) Run(run func()) *RankingStatusProvider_Status_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *RankingStatusProvider_Status_Call) Return(rankingStatus app.RankingStatus) *RankingStatusProvider_Status_Call {
	_c.Call.Return(rankingStatus)
	return _c
}

func (_c *RankingStatusProvider_Status_Call) RunAndReturn(run func() app.RankingStatus) *RankingStatusProvider_Status_Call {
	_c.Call.Return(run)
	return _c
}
