// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/steven-peralta/rosiebot/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewRankingProvider creates a new instance of RankingProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRankingProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *RankingProvider {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &RankingProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// RankingProvider is an autogenerated mock type for the RankingProvider type
type RankingProvider struct {
	mock.Mock
}

type RankingProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *RankingProvider) EXPECT() *RankingProvider_Expecter {
	return &RankingProvider_Expecter{mock: &_m.Mock}
}

// Current provides a mock function for the type RankingProvider
func (_mock *RankingProvider) Current() *domain.Ranking {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Current")
	}

	var r0 *domain.Ranking
	if returnFunc, ok := ret.Get(0).(func() *domain.Ranking); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Ranking)
		}
	}
	return r0
}

// RankingProvider_Current_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Current'
type RankingProvider_Current_Call struct {
	*mock.Call
}

// Current is a helper method to define mock.On call
func (_e *RankingProvider_Expecter) Current() *RankingProvider_Current_Call {
	return &RankingProvider_Current_Call{Call: _e.mock.On("Current")}
}

func (_c *RankingProvider_Current_Call) Run(run func()) *RankingProvider_Current_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *RankingProvider_Current_Call) Return(ranking *domain.Ranking) *RankingProvider_Current_Call {
	_c.Call.Return(ranking)
	return _c
}

func (_c *RankingProvider_Current_Call) RunAndReturn(run func() *domain.Ranking) *RankingProvider_Current_Call {
	_c.Call.Return(run)
	return _c
}
