// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/steven-peralta/rosiebot/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewRankingStore creates a new instance of RankingStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRankingStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *RankingStore {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &RankingStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// RankingStore is an autogenerated mock type for the RankingStore type
type RankingStore struct {
	mock.Mock
}

type RankingStore_Expecter struct {
	mock *mock.Mock
}

func (_m *RankingStore) EXPECT() *RankingStore_Expecter {
	return &RankingStore_Expecter{mock: &_m.Mock}
}

// LoadLatest provides a mock function for the type RankingStore
func (_mock *RankingStore) LoadLatest(ctx context.Context) (*domain.Ranking, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for LoadLatest")
	}

	var r0 *domain.Ranking
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*domain.Ranking, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *domain.Ranking); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Ranking)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RankingStore_LoadLatest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadLatest'
type RankingStore_LoadLatest_Call struct {
	*mock.Call
}

// LoadLatest is a helper method to define mock.On call
//   - ctx context.Context
func (_e *RankingStore_Expecter) LoadLatest(ctx any) *RankingStore_LoadLatest_Call {
	return &RankingStore_LoadLatest_Call{Call: _e.mock.On("LoadLatest", ctx)}
}

func (_c *RankingStore_LoadLatest_Call) Run(run func(ctx context.Context)) *RankingStore_LoadLatest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *RankingStore_LoadLatest_Call) Return(ranking *domain.Ranking, err error) *RankingStore_LoadLatest_Call {
	_c.Call.Return(ranking, err)
	return _c
}

func (_c *RankingStore_LoadLatest_Call) RunAndReturn(run func(ctx context.Context) (*domain.Ranking, error)) *RankingStore_LoadLatest_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type RankingStore
func (_mock *RankingStore) Save(ctx context.Context, r *domain.Ranking) error {
	ret := _mock.Called(ctx, r)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Ranking) error); ok {
		r0 = returnFunc(ctx, r)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// RankingStore_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type RankingStore_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - r *domain.Ranking
func (_e *RankingStore_Expecter) Save(ctx any, r any) *RankingStore_Save_Call {
	return &RankingStore_Save_Call{Call: _e.mock.On("Save", ctx, r)}
}

func (_c *RankingStore_Save_Call) Run(run func(ctx context.Context, r *domain.Ranking)) *RankingStore_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.Ranking
		if args[1] != nil {
			arg1 = args[1].(*domain.Ranking)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *RankingStore_Save_Call) Return(err error) *RankingStore_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *RankingStore_Save_Call) RunAndReturn(run func(ctx context.Context, r *domain.Ranking) error) *RankingStore_Save_Call {
	_c.Call.Return(run)
	return _c
}
