// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/steven-peralta/rosiebot/internal/app"
	"github.com/steven-peralta/rosiebot/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewWaifuSource creates a new instance of WaifuSource. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWaifuSource(t interface {
	mock.TestingT
	Cleanup(func())
}) *WaifuSource {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &WaifuSource{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// WaifuSource is an autogenerated mock type for the WaifuSource type
type WaifuSource struct {
	mock.Mock
}

type WaifuSource_Expecter struct {
	mock *mock.Mock
}

func (_m *WaifuSource) EXPECT() *WaifuSource_Expecter {
	return &WaifuSource_Expecter{mock: &_m.Mock}
}

// Daily provides a mock function for the type WaifuSource
func (_mock *WaifuSource) Daily(ctx context.Context) (domain.WaifuSummary, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Daily")
	}

	var r0 domain.WaifuSummary
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (domain.WaifuSummary, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) domain.WaifuSummary); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(domain.WaifuSummary)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// WaifuSource_Daily_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Daily'
type WaifuSource_Daily_Call struct {
	*mock.Call
}

// Daily is a helper method to define mock.On call
//   - ctx context.Context
func (_e *WaifuSource_Expecter) Daily(ctx any) *WaifuSource_Daily_Call {
	return &WaifuSource_Daily_Call{Call: _e.mock.On("Daily", ctx)}
}

func (_c *WaifuSource_Daily_Call) Run(run func(ctx context.Context)) *WaifuSource_Daily_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *WaifuSource_Daily_Call) Return(waifuSummary domain.WaifuSummary, err error) *WaifuSource_Daily_Call {
	_c.Call.Return(waifuSummary, err)
	return _c
}

func (_c *WaifuSource_Daily_Call) RunAndReturn(run func(ctx context.Context) (domain.WaifuSummary, error)) *WaifuSource_Daily_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type WaifuSource
func (_mock *WaifuSource) Get(ctx context.Context, slug string) (domain.Waifu, error) {
	ret := _mock.Called(ctx, slug)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 domain.Waifu
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (domain.Waifu, error)); ok {
		return returnFunc(ctx, slug)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) domain.Waifu); ok {
		r0 = returnFunc(ctx, slug)
	} else {
		r0 = ret.Get(0).(domain.Waifu)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, slug)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// WaifuSource_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type WaifuSource_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - slug string
func (_e *WaifuSource_Expecter) Get(ctx any, slug any) *WaifuSource_Get_Call {
	return &WaifuSource_Get_Call{Call: _e.mock.On("Get", ctx, slug)}
}

func (_c *WaifuSource_Get_Call) Run(run func(ctx context.Context, slug string)) *WaifuSource_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *WaifuSource_Get_Call) Return(waifu domain.Waifu, err error) *WaifuSource_Get_Call {
	_c.Call.Return(waifu, err)
	return _c
}

func (_c *WaifuSource_Get_Call) RunAndReturn(run func(ctx context.Context, slug string) (domain.Waifu, error)) *WaifuSource_Get_Call {
	_c.Call.Return(run)
	return _c
}

// ListCharacters provides a mock function for the type WaifuSource
func (_mock *WaifuSource) ListCharacters(ctx context.Context, page int) (app.SearchPage, error) {
	ret := _mock.Called(ctx, page)

	if len(ret) == 0 {
		panic("no return value specified for ListCharacters")
	}

	var r0 app.SearchPage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (app.SearchPage, error)); ok {
		return returnFunc(ctx, page)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) app.SearchPage); ok {
		r0 = returnFunc(ctx, page)
	} else {
		r0 = ret.Get(0).(app.SearchPage)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, page)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// WaifuSource_ListCharacters_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListCharacters'
type WaifuSource_ListCharacters_Call struct {
	*mock.Call
}

// ListCharacters is a helper method to define mock.On call
//   - ctx context.Context
//   - page int
func (_e *WaifuSource_Expecter) ListCharacters(ctx any, page any) *WaifuSource_ListCharacters_Call {
	return &WaifuSource_ListCharacters_Call{Call: _e.mock.On("ListCharacters", ctx, page)}
}

func (_c *WaifuSource_ListCharacters_Call) Run(run func(ctx context.Context, page int)) *WaifuSource_ListCharacters_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *WaifuSource_ListCharacters_Call) Return(searchPage app.SearchPage, err error) *WaifuSource_ListCharacters_Call {
	_c.Call.Return(searchPage, err)
	return _c
}

func (_c *WaifuSource_ListCharacters_Call) RunAndReturn(run func(ctx context.Context, page int) (app.SearchPage, error)) *WaifuSource_ListCharacters_Call {
	_c.Call.Return(run)
	return _c
}

// PopularPage provides a mock function for the type WaifuSource
func (_mock *WaifuSource) PopularPage(ctx context.Context, page int) (app.PopularPage, error) {
	ret := _mock.Called(ctx, page)

	if len(ret) == 0 {
		panic("no return value specified for PopularPage")
	}

	var r0 app.PopularPage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (app.PopularPage, error)); ok {
		return returnFunc(ctx, page)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) app.PopularPage); ok {
		r0 = returnFunc(ctx, page)
	} else {
		r0 = ret.Get(0).(app.PopularPage)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, page)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// WaifuSource_PopularPage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PopularPage'
type WaifuSource_PopularPage_Call struct {
	*mock.Call
}

// PopularPage is a helper method to define mock.On call
//   - ctx context.Context
//   - page int
func (_e *WaifuSource_Expecter) PopularPage(ctx any, page any) *WaifuSource_PopularPage_Call {
	return &WaifuSource_PopularPage_Call{Call: _e.mock.On("PopularPage", ctx, page)}
}

func (_c *WaifuSource_PopularPage_Call) Run(run func(ctx context.Context, page int)) *WaifuSource_PopularPage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *WaifuSource_PopularPage_Call) Return(popularPage app.PopularPage, err error) *WaifuSource_PopularPage_Call {
	_c.Call.Return(popularPage, err)
	return _c
}

func (_c *WaifuSource_PopularPage_Call) RunAndReturn(run func(ctx context.Context, page int) (app.PopularPage, error)) *WaifuSource_PopularPage_Call {
	_c.Call.Return(run)
	return _c
}

// Random provides a mock function for the type WaifuSource
func (_mock *WaifuSource) Random(ctx context.Context) (domain.WaifuSummary, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Random")
	}

	var r0 domain.WaifuSummary
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (domain.WaifuSummary, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) domain.WaifuSummary); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(domain.WaifuSummary)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// WaifuSource_Random_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Random'
type WaifuSource_Random_Call struct {
	*mock.Call
}

// Random is a helper method to define mock.On call
//   - ctx context.Context
func (_e *WaifuSource_Expecter) Random(ctx any) *WaifuSource_Random_Call {
	return &WaifuSource_Random_Call{Call: _e.mock.On("Random", ctx)}
}

func (_c *WaifuSource_Random_Call) Run(run func(ctx context.Context)) *WaifuSource_Random_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *WaifuSource_Random_Call) Return(waifuSummary domain.WaifuSummary, err error) *WaifuSource_Random_Call {
	_c.Call.Return(waifuSummary, err)
	return _c
}

func (_c *WaifuSource_Random_Call) RunAndReturn(run func(ctx context.Context) (domain.WaifuSummary, error)) *WaifuSource_Random_Call {
	_c.Call.Return(run)
	return _c
}

// SearchWaifus provides a mock function for the type WaifuSource
func (_mock *WaifuSource) SearchWaifus(ctx context.Context, term string, page int) (app.SearchPage, error) {
	ret := _mock.Called(ctx, term, page)

	if len(ret) == 0 {
		panic("no return value specified for SearchWaifus")
	}

	var r0 app.SearchPage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int) (app.SearchPage, error)); ok {
		return returnFunc(ctx, term, page)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int) app.SearchPage); ok {
		r0 = returnFunc(ctx, term, page)
	} else {
		r0 = ret.Get(0).(app.SearchPage)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int) error); ok {
		r1 = returnFunc(ctx, term, page)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// WaifuSource_SearchWaifus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchWaifus'
type WaifuSource_SearchWaifus_Call struct {
	*mock.Call
}

// SearchWaifus is a helper method to define mock.On call
//   - ctx context.Context
//   - term string
//   - page int
func (_e *WaifuSource_Expecter) SearchWaifus(ctx any, term any, page any) *WaifuSource_SearchWaifus_Call {
	return &WaifuSource_SearchWaifus_Call{Call: _e.mock.On("SearchWaifus", ctx, term, page)}
}

func (_c *WaifuSource_SearchWaifus_Call) Run(run func(ctx context.Context, term string, page int)) *WaifuSource_SearchWaifus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *WaifuSource_SearchWaifus_Call) Return(searchPage app.SearchPage, err error) *WaifuSource_SearchWaifus_Call {
	_c.Call.Return(searchPage, err)
	return _c
}

func (_c *WaifuSource_SearchWaifus_Call) RunAndReturn(run func(ctx context.Context, term string, page int) (app.SearchPage, error)) *WaifuSource_SearchWaifus_Call {
	_c.Call.Return(run)
	return _c
}

// SearchWorks provides a mock function for the type WaifuSource
func (_mock *WaifuSource) SearchWorks(ctx context.Context, term string) ([]domain.Series, error) {
	ret := _mock.Called(ctx, term)

	if len(ret) == 0 {
		panic("no return value specified for SearchWorks")
	}

	var r0 []domain.Series
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]domain.Series, error)); ok {
		return returnFunc(ctx, term)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []domain.Series); ok {
		r0 = returnFunc(ctx, term)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Series)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, term)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// WaifuSource_SearchWorks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchWorks'
type WaifuSource_SearchWorks_Call struct {
	*mock.Call
}

// SearchWorks is a helper method to define mock.On call
//   - ctx context.Context
//   - term string
func (_e *WaifuSource_Expecter) SearchWorks(ctx any, term any) *WaifuSource_SearchWorks_Call {
	return &WaifuSource_SearchWorks_Call{Call: _e.mock.On("SearchWorks", ctx, term)}
}

func (_c *WaifuSource_SearchWorks_Call) Run(run func(ctx context.Context, term string)) *WaifuSource_SearchWorks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *WaifuSource_SearchWorks_Call) Return(seriess []domain.Series, err error) *WaifuSource_SearchWorks_Call {
	_c.Call.Return(seriess, err)
	return _c
}

func (_c *WaifuSource_SearchWorks_Call) RunAndReturn(run func(ctx context.Context, term string) ([]domain.Series, error)) *WaifuSource_SearchWorks_Call {
	_c.Call.Return(run)
	return _c
}

// Work provides a mock function for the type WaifuSource
func (_mock *WaifuSource) Work(ctx context.Context, slug string) (domain.Series, error) {
	ret := _mock.Called(ctx, slug)

	if len(ret) == 0 {
		panic("no return value specified for Work")
	}

	var r0 domain.Series
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (domain.Series, error)); ok {
		return returnFunc(ctx, slug)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) domain.Series); ok {
		r0 = returnFunc(ctx, slug)
	} else {
		r0 = ret.Get(0).(domain.Series)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, slug)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// WaifuSource_Work_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Work'
type WaifuSource_Work_Call struct {
	*mock.Call
}

// Work is a helper method to define mock.On call
//   - ctx context.Context
//   - slug string
func (_e *WaifuSource_Expecter) Work(ctx any, slug any) *WaifuSource_Work_Call {
	return &WaifuSource_Work_Call{Call: _e.mock.On("Work", ctx, slug)}
}

func (_c *WaifuSource_Work_Call) Run(run func(ctx context.Context, slug string)) *WaifuSource_Work_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *WaifuSource_Work_Call) Return(series domain.Series, err error) *WaifuSource_Work_Call {
	_c.Call.Return(series, err)
	return _c
}

func (_c *WaifuSource_Work_Call) RunAndReturn(run func(ctx context.Context, slug string) (domain.Series, error)) *WaifuSource_Work_Call {
	_c.Call.Return(run)
	return _c
}

// WorkCharacters provides a mock function for the type WaifuSource
func (_mock *WaifuSource) WorkCharacters(ctx context.Context, slug string, page int) (app.SearchPage, error) {
	ret := _mock.Called(ctx, slug, page)

	if len(ret) == 0 {
		panic("no return value specified for WorkCharacters")
	}

	var r0 app.SearchPage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int) (app.SearchPage, error)); ok {
		return returnFunc(ctx, slug, page)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int) app.SearchPage); ok {
		r0 = returnFunc(ctx, slug, page)
	} else {
		r0 = ret.Get(0).(app.SearchPage)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int) error); ok {
		r1 = returnFunc(ctx, slug, page)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// WaifuSource_WorkCharacters_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WorkCharacters'
type WaifuSource_WorkCharacters_Call struct {
	*mock.Call
}

// WorkCharacters is a helper method to define mock.On call
//   - ctx context.Context
//   - slug string
//   - page int
func (_e *WaifuSource_Expecter) WorkCharacters(ctx any, slug any, page any) *WaifuSource_WorkCharacters_Call {
	return &WaifuSource_WorkCharacters_Call{Call: _e.mock.On("WorkCharacters", ctx, slug, page)}
}

func (_c *WaifuSource_WorkCharacters_Call) Run(run func(ctx context.Context, slug string, page int)) *WaifuSource_WorkCharacters_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *WaifuSource_WorkCharacters_Call) Return(searchPage app.SearchPage, err error) *WaifuSource_WorkCharacters_Call {
	_c.Call.Return(searchPage, err)
	return _c
}

func (_c *WaifuSource_WorkCharacters_Call) RunAndReturn(run func(ctx context.Context, slug string, page int) (app.SearchPage, error)) *WaifuSource_WorkCharacters_Call {
	_c.Call.Return(run)
	return _c
}
