// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	"github.com/steven-peralta/rosiebot/internal/app"
	"github.com/steven-peralta/rosiebot/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewWaifuCache creates a new instance of WaifuCache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWaifuCache(t interface {
	mock.TestingT
	Cleanup(func())
}) *WaifuCache {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &WaifuCache{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// WaifuCache is an autogenerated mock type for the WaifuCache type
type WaifuCache struct {
	mock.Mock
}

type WaifuCache_Expecter struct {
	mock *mock.Mock
}

func (_m *WaifuCache) EXPECT() *WaifuCache_Expecter {
	return &WaifuCache_Expecter{mock: &_m.Mock}
}

// GetPage provides a mock function for the type WaifuCache
func (_mock *WaifuCache) GetPage(ctx context.Context, key string) (app.CachedPage, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for GetPage")
	}

	var r0 app.CachedPage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (app.CachedPage, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) app.CachedPage); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Get(0).(app.CachedPage)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// WaifuCache_GetPage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPage'
type WaifuCache_GetPage_Call struct {
	*mock.Call
}

// GetPage is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *WaifuCache_Expecter) GetPage(ctx any, key any) *WaifuCache_GetPage_Call {
	return &WaifuCache_GetPage_Call{Call: _e.mock.On("GetPage", ctx, key)}
}

func (_c *WaifuCache_GetPage_Call) Run(run func(ctx context.Context, key string)) *WaifuCache_GetPage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *WaifuCache_GetPage_Call) Return(cachedPage app.CachedPage, err error) *WaifuCache_GetPage_Call {
	_c.Call.Return(cachedPage, err)
	return _c
}

func (_c *WaifuCache_GetPage_Call) RunAndReturn(run func(ctx context.Context, key string) (app.CachedPage, error)) *WaifuCache_GetPage_Call {
	_c.Call.Return(run)
	return _c
}

// GetSeries provides a mock function for the type WaifuCache
func (_mock *WaifuCache) GetSeries(ctx context.Context, key string) (app.CachedSeries, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for GetSeries")
	}

	var r0 app.CachedSeries
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (app.CachedSeries, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) app.CachedSeries); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Get(0).(app.CachedSeries)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// WaifuCache_GetSeries_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSeries'
type WaifuCache_GetSeries_Call struct {
	*mock.Call
}

// GetSeries is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *WaifuCache_Expecter) GetSeries(ctx any, key any) *WaifuCache_GetSeries_Call {
	return &WaifuCache_GetSeries_Call{Call: _e.mock.On("GetSeries", ctx, key)}
}

func (_c *WaifuCache_GetSeries_Call) Run(run func(ctx context.Context, key string)) *WaifuCache_GetSeries_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *WaifuCache_GetSeries_Call) Return(cachedSeries app.CachedSeries, err error) *WaifuCache_GetSeries_Call {
	_c.Call.Return(cachedSeries, err)
	return _c
}

func (_c *WaifuCache_GetSeries_Call) RunAndReturn(run func(ctx context.Context, key string) (app.CachedSeries, error)) *WaifuCache_GetSeries_Call {
	_c.Call.Return(run)
	return _c
}

// GetWaifu provides a mock function for the type WaifuCache
func (_mock *WaifuCache) GetWaifu(ctx context.Context, slug string) (app.CachedWaifu, error) {
	ret := _mock.Called(ctx, slug)

	if len(ret) == 0 {
		panic("no return value specified for GetWaifu")
	}

	var r0 app.CachedWaifu
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (app.CachedWaifu, error)); ok {
		return returnFunc(ctx, slug)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) app.CachedWaifu); ok {
		r0 = returnFunc(ctx, slug)
	} else {
		r0 = ret.Get(0).(app.CachedWaifu)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, slug)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// WaifuCache_GetWaifu_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWaifu'
type WaifuCache_GetWaifu_Call struct {
	*mock.Call
}

// GetWaifu is a helper method to define mock.On call
//   - ctx context.Context
//   - slug string
func (_e *WaifuCache_Expecter) GetWaifu(ctx any, slug any) *WaifuCache_GetWaifu_Call {
	return &WaifuCache_GetWaifu_Call{Call: _e.mock.On("GetWaifu", ctx, slug)}
}

func (_c *WaifuCache_GetWaifu_Call) Run(run func(ctx context.Context, slug string)) *WaifuCache_GetWaifu_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *WaifuCache_GetWaifu_Call) Return(cachedWaifu app.CachedWaifu, err error) *WaifuCache_GetWaifu_Call {
	_c.Call.Return(cachedWaifu, err)
	return _c
}

func (_c *WaifuCache_GetWaifu_Call) RunAndReturn(run func(ctx context.Context, slug string) (app.CachedWaifu, error)) *WaifuCache_GetWaifu_Call {
	_c.Call.Return(run)
	return _c
}

// Prune provides a mock function for the type WaifuCache
func (_mock *WaifuCache) Prune(ctx context.Context, unreadSince time.Time) (int64, error) {
	ret := _mock.Called(ctx, unreadSince)

	if len(ret) == 0 {
		panic("no return value specified for Prune")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time) (int64, error)); ok {
		return returnFunc(ctx, unreadSince)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time) int64); ok {
		r0 = returnFunc(ctx, unreadSince)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, time.Time) error); ok {
		r1 = returnFunc(ctx, unreadSince)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// WaifuCache_Prune_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Prune'
type WaifuCache_Prune_Call struct {
	*mock.Call
}

// Prune is a helper method to define mock.On call
//   - ctx context.Context
//   - unreadSince time.Time
func (_e *WaifuCache_Expecter) Prune(ctx any, unreadSince any) *WaifuCache_Prune_Call {
	return &WaifuCache_Prune_Call{Call: _e.mock.On("Prune", ctx, unreadSince)}
}

func (_c *WaifuCache_Prune_Call) Run(run func(ctx context.Context, unreadSince time.Time)) *WaifuCache_Prune_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 time.Time
		if args[1] != nil {
			arg1 = args[1].(time.Time)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *WaifuCache_Prune_Call) Return(n int64, err error) *WaifuCache_Prune_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *WaifuCache_Prune_Call) RunAndReturn(run func(ctx context.Context, unreadSince time.Time) (int64, error)) *WaifuCache_Prune_Call {
	_c.Call.Return(run)
	return _c
}

// PutPage provides a mock function for the type WaifuCache
func (_mock *WaifuCache) PutPage(ctx context.Context, key string, page app.SearchPage, fetchedAt time.Time) error {
	ret := _mock.Called(ctx, key, page, fetchedAt)

	if len(ret) == 0 {
		panic("no return value specified for PutPage")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, app.SearchPage, time.Time) error); ok {
		r0 = returnFunc(ctx, key, page, fetchedAt)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// WaifuCache_PutPage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PutPage'
type WaifuCache_PutPage_Call struct {
	*mock.Call
}

// PutPage is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - page app.SearchPage
//   - fetchedAt time.Time
func (_e *WaifuCache_Expecter) PutPage(ctx any, key any, page any, fetchedAt any) *WaifuCache_PutPage_Call {
	return &WaifuCache_PutPage_Call{Call: _e.mock.On("PutPage", ctx, key, page, fetchedAt)}
}

func (_c *WaifuCache_PutPage_Call) Run(run func(ctx context.Context, key string, page app.SearchPage, fetchedAt time.Time)) *WaifuCache_PutPage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 app.SearchPage
		if args[2] != nil {
			arg2 = args[2].(app.SearchPage)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *WaifuCache_PutPage_Call) Return(err error) *WaifuCache_PutPage_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *WaifuCache_PutPage_Call) RunAndReturn(run func(ctx context.Context, key string, page app.SearchPage, fetchedAt time.Time) error) *WaifuCache_PutPage_Call {
	_c.Call.Return(run)
	return _c
}

// PutSeries provides a mock function for the type WaifuCache
func (_mock *WaifuCache) PutSeries(ctx context.Context, key string, series []domain.Series, lastPage int, fetchedAt time.Time) error {
	ret := _mock.Called(ctx, key, series, lastPage, fetchedAt)

	if len(ret) == 0 {
		panic("no return value specified for PutSeries")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []domain.Series, int, time.Time) error); ok {
		r0 = returnFunc(ctx, key, series, lastPage, fetchedAt)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// WaifuCache_PutSeries_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PutSeries'
type WaifuCache_PutSeries_Call struct {
	*mock.Call
}

// PutSeries is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - series []domain.Series
//   - lastPage int
//   - fetchedAt time.Time
func (_e *WaifuCache_Expecter) PutSeries(ctx any, key any, series any, lastPage any, fetchedAt any) *WaifuCache_PutSeries_Call {
	return &WaifuCache_PutSeries_Call{Call: _e.mock.On("PutSeries", ctx, key, series, lastPage, fetchedAt)}
}

func (_c *WaifuCache_PutSeries_Call) Run(run func(ctx context.Context, key string, series []domain.Series, lastPage int, fetchedAt time.Time)) *WaifuCache_PutSeries_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []domain.Series
		if args[2] != nil {
			arg2 = args[2].([]domain.Series)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		var arg4 time.Time
		if args[4] != nil {
			arg4 = args[4].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *WaifuCache_PutSeries_Call) Return(err error) *WaifuCache_PutSeries_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *WaifuCache_PutSeries_Call) RunAndReturn(run func(ctx context.Context, key string, series []domain.Series, lastPage int, fetchedAt time.Time) error) *WaifuCache_PutSeries_Call {
	_c.Call.Return(run)
	return _c
}

// PutWaifu provides a mock function for the type WaifuCache
func (_mock *WaifuCache) PutWaifu(ctx context.Context, w domain.Waifu, fetchedAt time.Time) error {
	ret := _mock.Called(ctx, w, fetchedAt)

	if len(ret) == 0 {
		panic("no return value specified for PutWaifu")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Waifu, time.Time) error); ok {
		r0 = returnFunc(ctx, w, fetchedAt)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// WaifuCache_PutWaifu_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PutWaifu'
type WaifuCache_PutWaifu_Call struct {
	*mock.Call
}

// PutWaifu is a helper method to define mock.On call
//   - ctx context.Context
//   - w domain.Waifu
//   - fetchedAt time.Time
func (_e *WaifuCache_Expecter) PutWaifu(ctx any, w any, fetchedAt any) *WaifuCache_PutWaifu_Call {
	return &WaifuCache_PutWaifu_Call{Call: _e.mock.On("PutWaifu", ctx, w, fetchedAt)}
}

func (_c *WaifuCache_PutWaifu_Call) Run(run func(ctx context.Context, w domain.Waifu, fetchedAt time.Time)) *WaifuCache_PutWaifu_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Waifu
		if args[1] != nil {
			arg1 = args[1].(domain.Waifu)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *WaifuCache_PutWaifu_Call) Return(err error) *WaifuCache_PutWaifu_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *WaifuCache_PutWaifu_Call) RunAndReturn(run func(ctx context.Context, w domain.Waifu, fetchedAt time.Time) error) *WaifuCache_PutWaifu_Call {
	_c.Call.Return(run)
	return _c
}
