name: Build, test, & push Docker image

on:
  push:
    branches: [ staging ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node v22
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: yarn

      - name: Lint
        run: yarn lint

      - name: Build
        run: yarn run build:staging

      - name: Test
        run: yarn test

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: rosiebot
          path: |
            .aws
            scripts/prod-paths.js
            dist
            package.json
            tsconfig.json
            yarn.lock
            Dockerfile

  docker:
    needs: build
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_REPO: rosiebot

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: rosiebot

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $DOCKERHUB_USERNAME/$DOCKERHUB_REPO:$IMAGE_TAG .
          docker push $DOCKERHUB_USERNAME/$DOCKERHUB_REPO:$IMAGE_TAG
