name: Build, test, & push Docker image

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node v22
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build:prod

      - name: Test
        run: npm test

      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: rosiebot
          path: |
            .aws
            scripts/prod-paths.js
            dist
            package.json
            tsconfig.json
            package-lock.json
            Dockerfile

  docker:
    needs: build
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_REPO: rosiebot

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: rosiebot

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $DOCKERHUB_USERNAME/$DOCKERHUB_REPO:$IMAGE_TAG .
          docker tag $DOCKERHUB_USERNAME/$DOCKERHUB_REPO:$IMAGE_TAG $DOCKERHUB_USERNAME/$DOCKERHUB_REPO:latest
          docker push $DOCKERHUB_USERNAME/$DOCKERHUB_REPO:$IMAGE_TAG
          docker push $DOCKERHUB_USERNAME/$DOCKERHUB_REPO:latest
